/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registraclinic.telas;

import java.util.List;
import javax.swing.JOptionPane;
import registraclinic.aluno.Aluno;
import registraclinic.aluno.AlunoDAO;
import registraclinic.aluno.AlunoTableModel;
import registraclinic.paciente.Paciente;
import registraclinic.paciente.PacienteDAO;
import registraclinic.paciente.PacienteTableModel;
import registraclinic.util.Util;
import registraclinic.vincularpacientealuno.VincularPacienteAluno;
import registraclinic.vincularpacientealuno.VincularPacienteAlunoDAO;
import registraclinic.vincularpacientealuno.VincularPacienteAlunoTableModel;

/**
 *
 * @author Karlos Oliveira
 */
public class CadastrarVincularPacienteAluno extends javax.swing.JDialog {

    Aluno aluno;
    AlunoDAO alunoDAO;
    Paciente paciente;
    PacienteDAO pacienteDAO;
    VincularPacienteAluno vincularPacienteAluno;
    VincularPacienteAlunoDAO vincularPacienteAlunoDAO;

    public CadastrarVincularPacienteAluno(java.awt.Frame parent, boolean modal) {
        initComponents();
        btExcluir.setEnabled(false);
        getRootPane().setDefaultButton(btSalvar);
        aluno = new Aluno();
        alunoDAO = new AlunoDAO();
        pacienteDAO = new PacienteDAO();
        vincularPacienteAluno = new VincularPacienteAluno();
        vincularPacienteAlunoDAO = new VincularPacienteAlunoDAO();
        txtAluno.setEnabled(false);
        txtPaciente.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPaciente = new javax.swing.JButton();
        jlNomeUsuario5 = new javax.swing.JLabel();
        btVoltar = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jcSituacaoPaciente = new javax.swing.JComboBox<>();
        btLimpar = new javax.swing.JButton();
        txtPaciente = new javax.swing.JTextField();
        jlNomeUsuario1 = new javax.swing.JLabel();
        txtDataInicioConsulta = new javax.swing.JFormattedTextField();
        jlNomeUsuario4 = new javax.swing.JLabel();
        jlNomeUsuario = new javax.swing.JLabel();
        txtAluno = new javax.swing.JTextField();
        btnAluno = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        btnPaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/add-20-20.png"))); // NOI18N
        btnPaciente.setContentAreaFilled(false);
        btnPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPaciente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPaciente);
        btnPaciente.setBounds(590, 250, 30, 30);

        jlNomeUsuario5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario5.setText("Situação");
        getContentPane().add(jlNomeUsuario5);
        jlNomeUsuario5.setBounds(450, 290, 130, 20);

        btVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/voltar2.png"))); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.setContentAreaFilled(false);
        btVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar);
        btVoltar.setBounds(170, 420, 90, 70);

        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/pesquisa.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.setContentAreaFilled(false);
        btPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btPesquisar);
        btPesquisar.setBounds(400, 420, 99, 70);

        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/excluir_1.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setContentAreaFilled(false);
        btExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluir);
        btExcluir.setBounds(510, 420, 80, 70);

        jcSituacaoPaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcSituacaoPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "Em espera", "Ativo", "Inativo" }));
        jcSituacaoPaciente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jcSituacaoPaciente);
        jcSituacaoPaciente.setBounds(450, 310, 140, 30);

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/limpar_1.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setContentAreaFilled(false);
        btLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar);
        btLimpar.setBounds(300, 420, 80, 70);

        txtPaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPaciente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtPaciente.setMaximumSize(new java.awt.Dimension(8, 200));
        txtPaciente.setMinimumSize(new java.awt.Dimension(8, 200));
        txtPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtPaciente);
        txtPaciente.setBounds(100, 250, 490, 30);

        jlNomeUsuario1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario1.setText("Aluno");
        getContentPane().add(jlNomeUsuario1);
        jlNomeUsuario1.setBounds(100, 170, 100, 20);

        txtDataInicioConsulta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        try {
            txtDataInicioConsulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataInicioConsulta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtDataInicioConsulta);
        txtDataInicioConsulta.setBounds(100, 310, 170, 30);

        jlNomeUsuario4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario4.setText("Início do Atendimento");
        getContentPane().add(jlNomeUsuario4);
        jlNomeUsuario4.setBounds(100, 290, 170, 20);

        jlNomeUsuario.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario.setText("Paciente");
        getContentPane().add(jlNomeUsuario);
        jlNomeUsuario.setBounds(100, 230, 130, 20);

        txtAluno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAluno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtAluno.setMaximumSize(new java.awt.Dimension(8, 200));
        txtAluno.setMinimumSize(new java.awt.Dimension(8, 200));
        txtAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(txtAluno);
        txtAluno.setBounds(100, 190, 490, 30);

        btnAluno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/add-20-20.png"))); // NOI18N
        btnAluno.setContentAreaFilled(false);
        btnAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAluno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAluno);
        btnAluno.setBounds(590, 190, 30, 30);

        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/salvar_1.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setContentAreaFilled(false);
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar);
        btSalvar.setBounds(610, 420, 80, 70);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/VincularPacienteAoAluno.png"))); // NOI18N
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jLabel6.setMaximumSize(new java.awt.Dimension(699, 500));
        jLabel6.setMinimumSize(new java.awt.Dimension(699, 500));
        jLabel6.setPreferredSize(new java.awt.Dimension(699, 500));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(2, 0, 699, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        List<VincularPacienteAluno> lista;
        lista = vincularPacienteAlunoDAO.listar();
        VincularPacienteAlunoTableModel itm = new VincularPacienteAlunoTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Vínculo Aluno Paciente");
        if (objetoRetorno != null) {
            vincularPacienteAluno = vincularPacienteAlunoDAO.consultarObjetoId("idVincularPacienteAluno", objetoRetorno);
            txtAluno.setText(vincularPacienteAluno.getAluno().getNomeAluno());
            txtPaciente.setText(vincularPacienteAluno.getPaciente().getNomePaciente());
            txtDataInicioConsulta.setText(vincularPacienteAluno.getDataInicioAtendimento());
            jcSituacaoPaciente.setSelectedItem(vincularPacienteAluno.getPaciente().getSituacaoPaciente());
            btExcluir.setEnabled(true);

        }

    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        vincularPacienteAlunoDAO.excluir(vincularPacienteAluno);
        btLimparActionPerformed(null);

    }//GEN-LAST:event_btExcluirActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        Util.limparCamposGenerico(this);
        btExcluir.setEnabled(false);
        vincularPacienteAluno = new VincularPacienteAluno();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (txtAluno.getText().equals("") || txtDataInicioConsulta.getText().equals("")
                || txtAluno.getText().equals("")
                || txtPaciente.getText().equals("")
                || jcSituacaoPaciente.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Prencha todos os campos !!");
        } else {
            vincularPacienteAluno.setAluno(aluno);
            paciente.setSituacaoPaciente(jcSituacaoPaciente.getSelectedItem().toString());
            vincularPacienteAluno.setPaciente(paciente);
            vincularPacienteAluno.setDataInicioAtendimento(txtDataInicioConsulta.getText());
            vincularPacienteAlunoDAO.salvar(vincularPacienteAluno);
            Util.limparCamposGenerico(this);

        }
        vincularPacienteAluno = new VincularPacienteAluno();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();

    }//GEN-LAST:event_btVoltarActionPerformed

    private void btnPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacienteActionPerformed
        List<Paciente> lista;
        lista = (pacienteDAO.listar());
        PacienteTableModel itm = new PacienteTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Paciente");
        if (objetoRetorno != null) {
            paciente = pacienteDAO.consultarObjetoId("idPaciente", objetoRetorno);
            txtPaciente.setText(paciente.getNomePaciente());
            txtPaciente.setEnabled(false);
            jcSituacaoPaciente.setSelectedItem(paciente.getSituacaoPaciente());
        }
    }//GEN-LAST:event_btnPacienteActionPerformed

    private void txtPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPacienteActionPerformed

    private void txtAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlunoActionPerformed

    private void btnAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlunoActionPerformed
        List<Aluno> lista;
        lista = (alunoDAO.listar());
        AlunoTableModel itm = new AlunoTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Alunos");
        if (objetoRetorno != null) {
            aluno = alunoDAO.consultarObjetoId("idAluno", objetoRetorno);
            txtAluno.setText(aluno.getNomeAluno());
            txtAluno.setEnabled(false);
        }
    }//GEN-LAST:event_btnAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarVincularPacienteAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarVincularPacienteAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarVincularPacienteAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarVincularPacienteAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastrarVincularPacienteAluno dialog = new CadastrarVincularPacienteAluno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JButton btnAluno;
    private javax.swing.JButton btnPaciente;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> jcSituacaoPaciente;
    private javax.swing.JLabel jlNomeUsuario;
    private javax.swing.JLabel jlNomeUsuario1;
    private javax.swing.JLabel jlNomeUsuario4;
    private javax.swing.JLabel jlNomeUsuario5;
    private javax.swing.JTextField txtAluno;
    private javax.swing.JFormattedTextField txtDataInicioConsulta;
    private javax.swing.JTextField txtPaciente;
    // End of variables declaration//GEN-END:variables
}
