/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registraclinic.telas;

import java.text.SimpleDateFormat;
import java.util.Date;
import registraclinic.util.Util;
import java.util.List;
import javax.swing.JOptionPane;
import registraclinic.aluno.Aluno;
import registraclinic.aluno.AlunoDAO;
import registraclinic.aluno.AlunoTableModel;
import registraclinic.cidade.Cidade;
import registraclinic.cidade.CidadeDAO;
import registraclinic.cidade.CidadeTableModel;
import registraclinic.supervisor.Supervisor;
import registraclinic.supervisor.SupervisorDAO;
import registraclinic.supervisor.SupervisorTableModel;

/**
 *
 * @author Karlos Oliveira
 */
public class CadastroSupervisor extends javax.swing.JDialog {

    Supervisor supervisor = new Supervisor();
    SupervisorDAO supervisorDAO = new SupervisorDAO();
    Cidade cidade = new Cidade();
    CidadeDAO cidadeDAO = new CidadeDAO();
    SimpleDateFormat formatarData = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form TelaCadastroUsuario
     */
    public CadastroSupervisor(java.awt.Frame parent, boolean modal) {
        initComponents();
        getRootPane().setDefaultButton(btSalvar);

        btLimparActionPerformed(null);
        setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProduto2 = new javax.swing.JButton();
        tfLogin = new javax.swing.JTextField();
        jlLogin1 = new javax.swing.JLabel();
        jLObrigatorioSenha1 = new javax.swing.JLabel();
        tfSenha = new javax.swing.JPasswordField();
        jlSenha1 = new javax.swing.JLabel();
        jLObrigatorioLogin2 = new javax.swing.JLabel();
        jlTipoUsuario1 = new javax.swing.JLabel();
        jcTipoUsuario = new javax.swing.JComboBox<>();
        jlLogin2 = new javax.swing.JLabel();
        jlNomeUsuario5 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        jLObrigatorioNome5 = new javax.swing.JLabel();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        jLObrigatorioNome3 = new javax.swing.JLabel();
        jlNomeUsuario4 = new javax.swing.JLabel();
        jlNomeUsuario3 = new javax.swing.JLabel();
        jcEstado = new javax.swing.JComboBox();
        jLObrigatorioNome1 = new javax.swing.JLabel();
        jlLogin = new javax.swing.JLabel();
        jlTipoUsuario = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        jlNomeUsuario7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jcSexo = new javax.swing.JComboBox<>();
        txtCompleto = new javax.swing.JTextField();
        jlNomeUsuario1 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jlNomeUsuario8 = new javax.swing.JLabel();
        txtTurma = new javax.swing.JTextField();
        jlNomeUsuario2 = new javax.swing.JLabel();
        jLObrigatorioNome4 = new javax.swing.JLabel();
        txtRg = new javax.swing.JTextField();
        txtEspecializacao = new javax.swing.JTextField();
        jlNomeUsuario9 = new javax.swing.JLabel();
        jLObrigatorioLogin1 = new javax.swing.JLabel();
        jlNomeUsuario = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLObrigatorioNome6 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        jlNomeUsuario6 = new javax.swing.JLabel();
        jLObrigatorioNome8 = new javax.swing.JLabel();
        jLObrigatorioNome9 = new javax.swing.JLabel();
        jlSenha2 = new javax.swing.JLabel();
        jLObrigatorioLogin3 = new javax.swing.JLabel();
        jLObrigatorioNome10 = new javax.swing.JLabel();
        btVoltar = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jLObrigatorioNome = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        jLObrigatorioLogin = new javax.swing.JLabel();
        jLObrigatorioSenha = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 530));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        btnProduto2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProduto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/add20-20.png"))); // NOI18N
        btnProduto2.setContentAreaFilled(false);
        btnProduto2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProduto2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProduto2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProduto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduto2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnProduto2);
        btnProduto2.setBounds(350, 270, 30, 30);

        tfLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        getContentPane().add(tfLogin);
        tfLogin.setBounds(40, 390, 250, 30);

        jlLogin1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlLogin1.setText("Login:");
        getContentPane().add(jlLogin1);
        jlLogin1.setBounds(40, 370, 70, 19);

        jLObrigatorioSenha1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioSenha1.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioSenha1.setText("*");
        getContentPane().add(jLObrigatorioSenha1);
        jLObrigatorioSenha1.setBounds(290, 390, 10, 20);

        tfSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        tfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(tfSenha);
        tfSenha.setBounds(310, 390, 250, 30);

        jlSenha1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlSenha1.setText("Senha:");
        getContentPane().add(jlSenha1);
        jlSenha1.setBounds(310, 370, 60, 19);

        jLObrigatorioLogin2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioLogin2.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioLogin2.setText("*");
        getContentPane().add(jLObrigatorioLogin2);
        jLObrigatorioLogin2.setBounds(560, 390, 10, 10);

        jlTipoUsuario1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlTipoUsuario1.setText("Tipo de Usuário:");
        getContentPane().add(jlTipoUsuario1);
        jlTipoUsuario1.setBounds(390, 310, 130, 19);

        jcTipoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "Professor", "Supervisor" }));
        jcTipoUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        jcTipoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jcTipoUsuario);
        jcTipoUsuario.setBounds(390, 330, 150, 30);

        jlLogin2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlLogin2.setText("Endereço:");
        getContentPane().add(jlLogin2);
        jlLogin2.setBounds(40, 190, 90, 19);

        jlNomeUsuario5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario5.setText("Cidade:");
        getContentPane().add(jlNomeUsuario5);
        jlNomeUsuario5.setBounds(40, 250, 70, 20);

        txtCidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCidade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        txtCidade.setMaximumSize(new java.awt.Dimension(8, 200));
        txtCidade.setMinimumSize(new java.awt.Dimension(8, 200));
        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(txtCidade);
        txtCidade.setBounds(40, 270, 310, 30);

        txtEndereco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEndereco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        txtEndereco.setMaximumSize(new java.awt.Dimension(8, 200));
        txtEndereco.setMinimumSize(new java.awt.Dimension(8, 200));
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(txtEndereco);
        txtEndereco.setBounds(40, 210, 390, 30);

        jLObrigatorioNome5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome5.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome5.setText("*");
        getContentPane().add(jLObrigatorioNome5);
        jLObrigatorioNome5.setBounds(350, 270, 10, 10);

        try {
            txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataNascimento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtDataNascimento);
        txtDataNascimento.setBounds(220, 150, 110, 30);

        jLObrigatorioNome3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome3.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome3.setText("*");
        getContentPane().add(jLObrigatorioNome3);
        jLObrigatorioNome3.setBounds(330, 150, 10, 10);

        jlNomeUsuario4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario4.setText("Data de Nasc.:");
        getContentPane().add(jlNomeUsuario4);
        jlNomeUsuario4.setBounds(220, 130, 120, 20);

        jlNomeUsuario3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario3.setText("Estado:");
        getContentPane().add(jlNomeUsuario3);
        jlNomeUsuario3.setBounds(390, 250, 70, 20);

        jcEstado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-------", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jcEstado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        jcEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(jcEstado);
        jcEstado.setBounds(390, 270, 100, 30);

        jLObrigatorioNome1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome1.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome1.setText("*");
        getContentPane().add(jLObrigatorioNome1);
        jLObrigatorioNome1.setBounds(760, 150, 10, 10);

        jlLogin.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlLogin.setText("CPF:");
        getContentPane().add(jlLogin);
        jlLogin.setBounds(460, 70, 70, 19);

        jlTipoUsuario.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlTipoUsuario.setText("Sexo:");
        getContentPane().add(jlTipoUsuario);
        jlTipoUsuario.setBounds(40, 130, 70, 19);

        jlSenha.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlSenha.setText("RG:");
        getContentPane().add(jlSenha);
        jlSenha.setBounds(610, 70, 60, 19);

        txtCpf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 44, 143)));
        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtCpf);
        txtCpf.setBounds(460, 90, 130, 30);

        jlNomeUsuario7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario7.setText("E-mail:");
        getContentPane().add(jlNomeUsuario7);
        jlNomeUsuario7.setBounds(510, 130, 130, 20);

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        txtEmail.setMaximumSize(new java.awt.Dimension(8, 200));
        txtEmail.setMinimumSize(new java.awt.Dimension(8, 200));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail);
        txtEmail.setBounds(510, 150, 250, 30);

        jcSexo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "Masculino", "Feminino", "Não Informado" }));
        jcSexo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        jcSexo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jcSexo);
        jcSexo.setBounds(40, 150, 160, 30);

        txtCompleto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCompleto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        txtCompleto.setMaximumSize(new java.awt.Dimension(8, 200));
        txtCompleto.setMinimumSize(new java.awt.Dimension(8, 200));
        txtCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompletoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCompleto);
        txtCompleto.setBounds(510, 270, 250, 30);

        jlNomeUsuario1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario1.setText("Complemento:");
        getContentPane().add(jlNomeUsuario1);
        jlNomeUsuario1.setBounds(510, 250, 130, 20);

        txtNumero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNumero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        txtNumero.setMaximumSize(new java.awt.Dimension(8, 200));
        txtNumero.setMinimumSize(new java.awt.Dimension(8, 200));
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumero);
        txtNumero.setBounds(450, 210, 60, 30);

        jlNomeUsuario8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario8.setText("Turma:");
        getContentPane().add(jlNomeUsuario8);
        jlNomeUsuario8.setBounds(40, 310, 70, 20);

        txtTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTurma.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        txtTurma.setMaximumSize(new java.awt.Dimension(8, 200));
        txtTurma.setMinimumSize(new java.awt.Dimension(8, 200));
        txtTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTurmaActionPerformed(evt);
            }
        });
        getContentPane().add(txtTurma);
        txtTurma.setBounds(40, 330, 330, 30);

        jlNomeUsuario2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario2.setText("Nº.:");
        getContentPane().add(jlNomeUsuario2);
        jlNomeUsuario2.setBounds(450, 190, 40, 20);

        jLObrigatorioNome4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome4.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome4.setText("*");
        getContentPane().add(jLObrigatorioNome4);
        jLObrigatorioNome4.setBounds(430, 210, 10, 10);

        txtRg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtRg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        getContentPane().add(txtRg);
        txtRg.setBounds(610, 90, 150, 30);

        txtEspecializacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEspecializacao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        txtEspecializacao.setMaximumSize(new java.awt.Dimension(8, 200));
        txtEspecializacao.setMinimumSize(new java.awt.Dimension(8, 200));
        txtEspecializacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecializacaoActionPerformed(evt);
            }
        });
        getContentPane().add(txtEspecializacao);
        txtEspecializacao.setBounds(560, 330, 200, 30);

        jlNomeUsuario9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario9.setText("Especialização:");
        getContentPane().add(jlNomeUsuario9);
        jlNomeUsuario9.setBounds(560, 310, 130, 20);

        jLObrigatorioLogin1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioLogin1.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioLogin1.setText("*");
        getContentPane().add(jLObrigatorioLogin1);
        jLObrigatorioLogin1.setBounds(200, 150, 10, 10);

        jlNomeUsuario.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario.setText("Nome:");
        getContentPane().add(jlNomeUsuario);
        jlNomeUsuario.setBounds(40, 70, 60, 20);

        txtNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        txtNome.setMaximumSize(new java.awt.Dimension(8, 200));
        txtNome.setMinimumSize(new java.awt.Dimension(8, 200));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(40, 90, 400, 30);

        jLObrigatorioNome6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome6.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome6.setText("*");
        getContentPane().add(jLObrigatorioNome6);
        jLObrigatorioNome6.setBounds(510, 210, 10, 10);

        txtBairro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBairro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        txtBairro.setMaximumSize(new java.awt.Dimension(8, 200));
        txtBairro.setMinimumSize(new java.awt.Dimension(8, 200));
        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });
        getContentPane().add(txtBairro);
        txtBairro.setBounds(530, 210, 230, 30);

        txtTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 44, 143)));
        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(350, 150, 140, 30);

        jlNomeUsuario6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario6.setText("Bairro:");
        getContentPane().add(jlNomeUsuario6);
        jlNomeUsuario6.setBounds(530, 190, 60, 20);

        jLObrigatorioNome8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome8.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome8.setText("*");
        getContentPane().add(jLObrigatorioNome8);
        jLObrigatorioNome8.setBounds(540, 330, 10, 10);

        jLObrigatorioNome9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome9.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome9.setText("*");
        getContentPane().add(jLObrigatorioNome9);
        jLObrigatorioNome9.setBounds(370, 330, 10, 10);

        jlSenha2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlSenha2.setText("Telefone:");
        getContentPane().add(jlSenha2);
        jlSenha2.setBounds(350, 130, 100, 19);

        jLObrigatorioLogin3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioLogin3.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioLogin3.setText("*");
        getContentPane().add(jLObrigatorioLogin3);
        jLObrigatorioLogin3.setBounds(490, 150, 10, 10);

        jLObrigatorioNome10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome10.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome10.setText("*");
        getContentPane().add(jLObrigatorioNome10);
        jLObrigatorioNome10.setBounds(490, 270, 10, 10);

        btVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/voltar.png"))); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.setContentAreaFilled(false);
        btVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar);
        btVoltar.setBounds(30, 440, 90, 70);

        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/pesquisar.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.setContentAreaFilled(false);
        btPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btPesquisar);
        btPesquisar.setBounds(340, 440, 100, 70);

        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/excluir.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setContentAreaFilled(false);
        btExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluir);
        btExcluir.setBounds(460, 440, 80, 70);

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/limpar.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setContentAreaFilled(false);
        btLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar);
        btLimpar.setBounds(240, 440, 80, 70);

        jLObrigatorioNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome.setText("*");
        getContentPane().add(jLObrigatorioNome);
        jLObrigatorioNome.setBounds(440, 90, 10, 10);

        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/Salvar.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setContentAreaFilled(false);
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar);
        btSalvar.setBounds(690, 440, 80, 70);

        jLObrigatorioLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioLogin.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioLogin.setText("*");
        getContentPane().add(jLObrigatorioLogin);
        jLObrigatorioLogin.setBounds(760, 90, 10, 10);

        jLObrigatorioSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioSenha.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioSenha.setText("*");
        getContentPane().add(jLObrigatorioSenha);
        jLObrigatorioSenha.setBounds(590, 90, 10, 10);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/CadastroSupervisor.png"))); // NOI18N
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel6.setMaximumSize(new java.awt.Dimension(800, 530));
        jLabel6.setMinimumSize(new java.awt.Dimension(800, 530));
        jLabel6.setPreferredSize(new java.awt.Dimension(800, 530));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 800, 530);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        List<Supervisor> lista;
        lista = (supervisorDAO.listar());
        SupervisorTableModel itm = new SupervisorTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Aluno");
        if (objetoRetorno != null) {
            supervisor = supervisorDAO.consultarObjetoId("idAluno", objetoRetorno);
            txtNome.setText(supervisor.getNomeSupervisor());
            txtCpf.setText(supervisor.getCpfSupervisor());
            txtRg.setText(supervisor.getRgSupervisor());
            txtDataNascimento.setText(supervisor.getDataNascimentoSupervisor());
            txtEndereco.setText(supervisor.getEnderecoSupervisor());
            txtBairro.setText(supervisor.getBairroSupervisor());
            txtNumero.setText(supervisor.getEnderecoNumeroSupervisor());
            txtCidade.setText(supervisor.getCidadeSupervisor());
            txtTelefone.setText(supervisor.getTelefoneSupervisor());
            txtEmail.setText(supervisor.getEmailSupervisor());
            txtCompleto.setText(supervisor.getComplementoSupervisor());
            txtTurma.setText(supervisor.getTurmaSupervisor());
            txtEspecializacao.setText(supervisor.getEspecializaçãoSupervisor());
            tfLogin.setText(supervisor.getLoginSupervisor());
            tfSenha.setText(supervisor.getSenhaSupervisor());
            jcEstado.setSelectedItem(supervisor.getTelefoneSupervisor());
            jcSexo.setSelectedItem(supervisor.getSexoSupervisor());
            jcTipoUsuario.setSelectedItem(supervisor.getNivelAcessoSupervisor());

            btExcluir.setEnabled(true);
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        supervisorDAO.excluir(supervisor);
        btLimparActionPerformed(null);
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        Util.limparCamposGenerico(this);
        btExcluir.setEnabled(false);
        jcSexo.setSelectedIndex(0);
        supervisor = new Supervisor();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

        if (txtEndereco.getText().equals("") || txtCpf.getText().equals("")
                || txtDataNascimento.getText().equals("") || txtEndereco.getText().equals("")
                || txtEndereco.getText().equals("") || jcSexo.getSelectedItem().equals("-------")
                || txtRg.getText().equals("") || txtTelefone.getText().equals("") || tfLogin.getText().equals("")
                || tfSenha.getText().equals("") ) {
            JOptionPane.showMessageDialog(this, "Prencha todos os campos !!");
        } else {
            supervisor.setNomeSupervisor(txtNome.getText().toUpperCase());
            supervisor.setCpfSupervisor(txtCpf.getText());
            supervisor.setDataNascimentoSupervisor(txtDataNascimento.getText());
            supervisor.setEnderecoSupervisor(txtEndereco.getText());
            supervisor.setEnderecoNumeroSupervisor(txtNumero.getText());
            supervisor.setRgSupervisor(txtRg.getText());
            supervisor.setSexoSupervisor(jcSexo.getSelectedItem().toString());
            supervisor.setNivelAcessoSupervisor(jcTipoUsuario.getSelectedItem().toString());
            supervisor.setEstadoSupervisor(jcEstado.getSelectedItem().toString());
            supervisor.setCidadeSupervisor(txtCidade.getText());
            supervisor.setBairroSupervisor(txtBairro.getText());
            supervisor.setEmailSupervisor(txtEmail.getText());
            supervisor.setComplementoSupervisor(txtCompleto.getText());
            supervisor.setTurmaSupervisor(txtTurma.getText());
            supervisor.setTelefoneSupervisor(txtTelefone.getText());
            supervisor.setLoginSupervisor(tfLogin.getText());
            supervisor.setSenhaSupervisor(tfSenha.getText());
            supervisor.setEspecializaçãoSupervisor(txtEspecializacao.getText());

            supervisorDAO.salvar(supervisor);
            btLimparActionPerformed(null);

        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed

        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void jcEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcEstadoActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void btnProduto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduto2ActionPerformed
        List<Cidade> lista;
        lista = (cidadeDAO.listar());
        CidadeTableModel itm = new CidadeTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Cidade");
        if (objetoRetorno != null) {
            cidade = cidadeDAO.consultarObjetoId("idCidade", objetoRetorno);

            txtCidade.setText(cidade.getNomeCidade());
            txtCidade.setEnabled(false);

        }
    }//GEN-LAST:event_btnProduto2ActionPerformed

    private void txtCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompletoActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTurmaActionPerformed

    private void txtEspecializacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecializacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecializacaoActionPerformed

    private void tfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroSupervisor dialog = new CadastroSupervisor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JButton btnProduto2;
    private javax.swing.JLabel jLObrigatorioLogin;
    private javax.swing.JLabel jLObrigatorioLogin1;
    private javax.swing.JLabel jLObrigatorioLogin2;
    private javax.swing.JLabel jLObrigatorioLogin3;
    private javax.swing.JLabel jLObrigatorioNome;
    private javax.swing.JLabel jLObrigatorioNome1;
    private javax.swing.JLabel jLObrigatorioNome10;
    private javax.swing.JLabel jLObrigatorioNome3;
    private javax.swing.JLabel jLObrigatorioNome4;
    private javax.swing.JLabel jLObrigatorioNome5;
    private javax.swing.JLabel jLObrigatorioNome6;
    private javax.swing.JLabel jLObrigatorioNome8;
    private javax.swing.JLabel jLObrigatorioNome9;
    private javax.swing.JLabel jLObrigatorioSenha;
    private javax.swing.JLabel jLObrigatorioSenha1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox jcEstado;
    private javax.swing.JComboBox<String> jcSexo;
    private javax.swing.JComboBox<String> jcTipoUsuario;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JLabel jlLogin1;
    private javax.swing.JLabel jlLogin2;
    private javax.swing.JLabel jlNomeUsuario;
    private javax.swing.JLabel jlNomeUsuario1;
    private javax.swing.JLabel jlNomeUsuario2;
    private javax.swing.JLabel jlNomeUsuario3;
    private javax.swing.JLabel jlNomeUsuario4;
    private javax.swing.JLabel jlNomeUsuario5;
    private javax.swing.JLabel jlNomeUsuario6;
    private javax.swing.JLabel jlNomeUsuario7;
    private javax.swing.JLabel jlNomeUsuario8;
    private javax.swing.JLabel jlNomeUsuario9;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlSenha1;
    private javax.swing.JLabel jlSenha2;
    private javax.swing.JLabel jlTipoUsuario;
    private javax.swing.JLabel jlTipoUsuario1;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JPasswordField tfSenha;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCompleto;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEspecializacao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRg;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JTextField txtTurma;
    // End of variables declaration//GEN-END:variables
}
