/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registraclinic.telas;

import registraclinic.util.Util;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import registraclinic.atendimento.Atendimento;
import registraclinic.atendimento.AtendimentoCadastroTableModel;
import registraclinic.atendimento.AtendimentoDAO;
import registraclinic.atendimento.AtendimentoTableModel;
import registraclinic.paciente.Paciente;
import registraclinic.paciente.PacienteDAO;
import registraclinic.paciente.PacienteTableModel;
import registraclinic.prioridadeatendimento.PrioridadeAtendimento;
import registraclinic.prioridadeatendimento.PrioridadeAtendimentoDAO;
import registraclinic.prioridadeatendimento.PrioridadeAtendimentoTableModel;

/**
 *
 * @author Karlos Oliveira
 */
public class CadastroPrioridadeAtendimento extends javax.swing.JDialog {

    Paciente paciente = new Paciente();
    PacienteDAO pacienteDAO = new PacienteDAO();
    Atendimento atendimento = new Atendimento();
    AtendimentoDAO atendimentoDAO = new AtendimentoDAO();
    PrioridadeAtendimento prioridadeAtendimento = new PrioridadeAtendimento();
    PrioridadeAtendimentoDAO prioridadeAtendimentoDAO = new PrioridadeAtendimentoDAO();
    List<PrioridadeAtendimento> listaAtendimentos = new ArrayList<>();
    List<Paciente> pacientes = new ArrayList<>();
    List<Atendimento> atendimentos = new ArrayList<>();
    SimpleDateFormat formatarData = new SimpleDateFormat("dd/MM/yyyy");

    public CadastroPrioridadeAtendimento(java.awt.Frame parent, boolean modal) {
        initComponents();
        getRootPane().setDefaultButton(btSalvar);
        btLimparActionPerformed(null);
        setModal(true);
        txtPaciente.setEnabled(false);
        txtAtendimento.setEnabled(false);
    }


    public void addPrioridade() {

        if (prioridadeAtendimento != null) {
            prioridadeAtendimento = new PrioridadeAtendimento();
            prioridadeAtendimento.setAtendimento(atendimento);
            prioridadeAtendimento.setPaciente(paciente);
            listaAtendimentos.add(prioridadeAtendimento);
        } else {
            System.out.println("Selecione um atendimento!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDestino = new javax.swing.ButtonGroup();
        btVoltar = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        btnAtendimento = new javax.swing.JButton();
        txtAtendimento = new javax.swing.JTextField();
        jlNomeUsuario6 = new javax.swing.JLabel();
        jLObrigatorioNome4 = new javax.swing.JLabel();
        btExcluir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        jlNomeUsuario5 = new javax.swing.JLabel();
        txtPaciente = new javax.swing.JTextField();
        btnPaciente = new javax.swing.JButton();
        jLObrigatorioNome3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(773, 521));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        btVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.setContentAreaFilled(false);
        btVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btVoltar.setDefaultCapable(false);
        btVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar);
        btVoltar.setBounds(30, 430, 90, 70);

        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.setContentAreaFilled(false);
        btPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btPesquisar);
        btPesquisar.setBounds(340, 430, 100, 70);

        btnAtendimento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAtendimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/add-20-20.png"))); // NOI18N
        btnAtendimento.setToolTipText("Clique aqui para adicionar um novo estoque do produto selecionado.");
        btnAtendimento.setContentAreaFilled(false);
        btnAtendimento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAtendimento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtendimento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtendimentoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtendimento);
        btnAtendimento.setBounds(430, 110, 30, 30);

        txtAtendimento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAtendimento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        txtAtendimento.setMaximumSize(new java.awt.Dimension(8, 200));
        txtAtendimento.setMinimumSize(new java.awt.Dimension(8, 200));
        txtAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAtendimentoActionPerformed(evt);
            }
        });
        getContentPane().add(txtAtendimento);
        txtAtendimento.setBounds(50, 110, 370, 30);

        jlNomeUsuario6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario6.setText("Atendimento");
        getContentPane().add(jlNomeUsuario6);
        jlNomeUsuario6.setBounds(50, 90, 120, 20);

        jLObrigatorioNome4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome4.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome4.setText("*");
        getContentPane().add(jLObrigatorioNome4);
        jLObrigatorioNome4.setBounds(420, 100, 10, 30);

        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setContentAreaFilled(false);
        btExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluir);
        btExcluir.setBounds(450, 430, 80, 70);

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setContentAreaFilled(false);
        btLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar);
        btLimpar.setBounds(240, 430, 80, 70);

        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setContentAreaFilled(false);
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar);
        btSalvar.setBounds(670, 430, 80, 70);

        jlNomeUsuario5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario5.setText("Paciente");
        getContentPane().add(jlNomeUsuario5);
        jlNomeUsuario5.setBounds(50, 20, 70, 20);

        txtPaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPaciente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        txtPaciente.setMaximumSize(new java.awt.Dimension(8, 200));
        txtPaciente.setMinimumSize(new java.awt.Dimension(8, 200));
        txtPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtPaciente);
        txtPaciente.setBounds(50, 40, 370, 30);

        btnPaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/add-20-20.png"))); // NOI18N
        btnPaciente.setContentAreaFilled(false);
        btnPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPaciente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPaciente);
        btnPaciente.setBounds(430, 40, 30, 30);

        jLObrigatorioNome3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome3.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome3.setText("*");
        getContentPane().add(jLObrigatorioNome3);
        jLObrigatorioNome3.setBounds(420, 30, 10, 30);

        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel6.setMaximumSize(new java.awt.Dimension(773, 520));
        jLabel6.setMinimumSize(new java.awt.Dimension(773, 520));
        jLabel6.setPreferredSize(new java.awt.Dimension(773, 520));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(2, 0, 770, 520);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed

        if (prioridadeAtendimento.getIdPrioridadeAtendimento() != 0) {
            listaAtendimentos = prioridadeAtendimentoDAO.checkExistseq("idPrioridadeAtendimento", prioridadeAtendimento.getIdPrioridadeAtendimento());
            if (listaAtendimentos != null) {
                atualizarTabelaAtendimento();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um paciente!");
        }

    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        if (tbAtendimento.getSelectedRow() > -1) {
            if (listaAtendimentos.get(tbAtendimento.getSelectedRow()).getIdPrioridadeAtendimento() != 0) {
                prioridadeAtendimentoDAO.excluir(listaAtendimentos.get(tbAtendimento.getSelectedRow()));
            }
            listaAtendimentos.remove(tbAtendimento.getSelectedRow());
            atualizarTabelaAtendimento();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um produto!",
                    "ERRO", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btExcluirActionPerformed


    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        String atendimentosSalvos = "";
        for (PrioridadeAtendimento atendi : listaAtendimentos) {
            if (atendi.getIdPrioridadeAtendimento() == 0) {
                if (prioridadeAtendimentoDAO.salvar(atendi)) {
                    atendimentosSalvos = "ATENDIMENTO: " + atendi.getAtendimento().getNomeAtendimento();
                    prioridadeAtendimento = new PrioridadeAtendimento();
                }
            }
        }
        JOptionPane.showMessageDialog(this, "Lista de atendimento de : " + txtPaciente.getText() + "\n\n" + atendimentosSalvos);
        btLimparActionPerformed(null);
    }//GEN-LAST:event_btSalvarActionPerformed


    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void txtPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPacienteActionPerformed

    private void btnPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacienteActionPerformed
        List<Paciente> lista;
        lista = (pacienteDAO.listar());
        PacienteTableModel itm = new PacienteTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Paciente");
        if (objetoRetorno != null) {
            paciente = pacienteDAO.consultarObjetoId("idPessoa", objetoRetorno);
            txtPaciente.setText(paciente.getNomePessoa());
            txtPaciente.setEnabled(false);
            pacientes = pacienteDAO.checkExistseq("idPessoa", paciente.getIdPessoa());
            //atualizarTabelaAtendimento();
        }
    }//GEN-LAST:event_btnPacienteActionPerformed


    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        Util.limparCamposGenerico(this);
        listaAtendimentos = new ArrayList<>();
        atualizarTabelaAtendimento();
        atendimento = new Atendimento();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btnAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtendimentoActionPerformed
        List<Atendimento> lista;
        lista = (atendimentoDAO.listar());
        AtendimentoTableModel itm = new AtendimentoTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Atendimento");
        if (objetoRetorno != null) {
            atendimento = atendimentoDAO.consultarObjetoId("idAtendimento", objetoRetorno);
            txtAtendimento.setText(atendimento.getNomeAtendimento());
            txtPaciente.setEnabled(false);
            atendimentos = atendimentoDAO.checkExistseq("idAtendimento", atendimento.getIdAtendimento());

        }
        //addPrioridade();
    }//GEN-LAST:event_btnAtendimentoActionPerformed

    private void txtAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAtendimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAtendimentoActionPerformed

    public void addAPorraToda() {
        if (paciente != null || atendimento != null) {
            prioridadeAtendimento = new PrioridadeAtendimento();
            prioridadeAtendimento.setPaciente(paciente);
            prioridadeAtendimento.setAtendimento(atendimento);
            listaAtendimentos.add(prioridadeAtendimento);
            atualizarTabelaAtendimento();
        } else {
            System.out.println("Selecione um paciente!");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPrioridadeAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPrioridadeAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPrioridadeAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPrioridadeAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroPrioridadeAtendimento dialog = new CadastroPrioridadeAtendimento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JButton btnAtendimento;
    private javax.swing.JButton btnPaciente;
    private javax.swing.ButtonGroup grupoDestino;
    private javax.swing.JLabel jLObrigatorioNome3;
    private javax.swing.JLabel jLObrigatorioNome4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jlNomeUsuario5;
    private javax.swing.JLabel jlNomeUsuario6;
    private javax.swing.JTextField txtAtendimento;
    private javax.swing.JTextField txtPaciente;
    // End of variables declaration//GEN-END:variables
}
