/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registraclinic.telas;

import registraclinic.util.Util;
import java.util.List;
import javax.swing.JOptionPane;
import registraclinic.atendimento.Atendimento;
import registraclinic.atendimento.AtendimentoDAO;
import registraclinic.atendimento.AtendimentoTableModel;
import registraclinic.paciente.Paciente;
import registraclinic.paciente.PacienteDAO;
import registraclinic.paciente.PacienteTableModel;
import registraclinic.prioridadeatendimento.PrioridadeAtendimento;
import registraclinic.prioridadeatendimento.PrioridadeAtendimentoDAO;
import registraclinic.prioridadeatendimento.PrioridadeAtendimentoTableModel;

/**
 *
 * @author Karlos Oliveira
 */
public class CadastroTriagem extends javax.swing.JDialog {

    Paciente paciente = new Paciente();
    PacienteDAO pacienteDAO = new PacienteDAO();
    Atendimento atendimento = new Atendimento();
    AtendimentoDAO atendimentoDAO = new AtendimentoDAO();
    PrioridadeAtendimento prioridadeAtendimento = new PrioridadeAtendimento();
    PrioridadeAtendimentoDAO prioridadeAtendimentoDAO = new PrioridadeAtendimentoDAO();

    public CadastroTriagem(java.awt.Frame parent, boolean modal) {
        initComponents();
        getRootPane().setDefaultButton(btSalvar);
        btLimparActionPerformed(null);
        setModal(true);
        txtPaciente.setEnabled(false);
        txtAtendimento.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoPrioridade = new javax.swing.ButtonGroup();
        btVoltar = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        btnAtendimento = new javax.swing.JButton();
        txtAtendimento = new javax.swing.JTextField();
        jlNomeUsuario6 = new javax.swing.JLabel();
        jLObrigatorioNome4 = new javax.swing.JLabel();
        btExcluir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        jrAzul = new javax.swing.JRadioButton();
        verde1 = new javax.swing.JLabel();
        jlNomeUsuario5 = new javax.swing.JLabel();
        jrAmarelo = new javax.swing.JRadioButton();
        jrLaranja = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txtPaciente = new javax.swing.JTextField();
        verde = new javax.swing.JLabel();
        jrVerde = new javax.swing.JRadioButton();
        amarelo = new javax.swing.JLabel();
        laranja = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btnPaciente = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLObrigatorioNome3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 521));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        btVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/voltar_1.png"))); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.setContentAreaFilled(false);
        btVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btVoltar.setDefaultCapable(false);
        btVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar);
        btVoltar.setBounds(30, 440, 90, 70);

        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/pesquisa.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.setContentAreaFilled(false);
        btPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btPesquisar);
        btPesquisar.setBounds(360, 440, 100, 70);

        btnAtendimento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAtendimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/add-20-20.png"))); // NOI18N
        btnAtendimento.setToolTipText("Clique aqui para adicionar um novo estoque do produto selecionado.");
        btnAtendimento.setContentAreaFilled(false);
        btnAtendimento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAtendimento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtendimento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtendimentoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtendimento);
        btnAtendimento.setBounds(770, 90, 30, 30);

        txtAtendimento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAtendimento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        txtAtendimento.setMaximumSize(new java.awt.Dimension(8, 200));
        txtAtendimento.setMinimumSize(new java.awt.Dimension(8, 200));
        txtAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAtendimentoActionPerformed(evt);
            }
        });
        getContentPane().add(txtAtendimento);
        txtAtendimento.setBounds(430, 90, 340, 30);

        jlNomeUsuario6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario6.setText("Atendimento");
        getContentPane().add(jlNomeUsuario6);
        jlNomeUsuario6.setBounds(430, 70, 120, 20);

        jLObrigatorioNome4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome4.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome4.setText("*");
        getContentPane().add(jLObrigatorioNome4);
        jLObrigatorioNome4.setBounds(760, 80, 9, 10);

        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/excluir_1.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setContentAreaFilled(false);
        btExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluir);
        btExcluir.setBounds(500, 440, 80, 70);

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/limpar_1.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setContentAreaFilled(false);
        btLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar);
        btLimpar.setBounds(240, 440, 80, 70);

        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/salvar_1.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setContentAreaFilled(false);
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar);
        btSalvar.setBounds(720, 440, 80, 70);

        grupoPrioridade.add(jrAzul);
        jrAzul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrAzul.setText("Azul");
        jrAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrAzulActionPerformed(evt);
            }
        });
        getContentPane().add(jrAzul);
        jrAzul.setBounds(60, 390, 70, 23);

        verde1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/azul.png"))); // NOI18N
        getContentPane().add(verde1);
        verde1.setBounds(20, 380, 40, 40);

        jlNomeUsuario5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario5.setText("Paciente");
        getContentPane().add(jlNomeUsuario5);
        jlNomeUsuario5.setBounds(20, 70, 70, 20);

        grupoPrioridade.add(jrAmarelo);
        jrAmarelo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrAmarelo.setText("Amarelo");
        getContentPane().add(jrAmarelo);
        jrAmarelo.setBounds(60, 250, 90, 23);

        grupoPrioridade.add(jrLaranja);
        jrLaranja.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrLaranja.setText("Laranja");
        getContentPane().add(jrLaranja);
        jrLaranja.setBounds(60, 180, 80, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel7.setText("Prioridade de Atendimento");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 130, 300, 30);

        txtPaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPaciente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        txtPaciente.setMaximumSize(new java.awt.Dimension(8, 200));
        txtPaciente.setMinimumSize(new java.awt.Dimension(8, 200));
        txtPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtPaciente);
        txtPaciente.setBounds(20, 90, 340, 30);

        verde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/verde.png"))); // NOI18N
        getContentPane().add(verde);
        verde.setBounds(20, 310, 40, 40);

        grupoPrioridade.add(jrVerde);
        jrVerde.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrVerde.setText("Verde");
        jrVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrVerdeActionPerformed(evt);
            }
        });
        getContentPane().add(jrVerde);
        jrVerde.setBounds(60, 320, 70, 23);

        amarelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/amarelo.png"))); // NOI18N
        getContentPane().add(amarelo);
        amarelo.setBounds(20, 240, 40, 40);

        laranja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/laranja.png"))); // NOI18N
        getContentPane().add(laranja);
        laranja.setBounds(20, 170, 40, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Paciente com patologia crônica não agudizada que pode aguardar - encaixar quando possível");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 380, 640, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Paciente necessita de atendimento o mais protamente possível - encaixá-lo no máximo em 7 dias");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 170, 650, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Paciente com patologia crônica que pode aguardar, mas sem tanta espera - encaixar dentro de 1 mês");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 310, 630, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Paciente necessita iniciar a fisioterapia nos próximos 15 dias");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 240, 440, 40);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 430, 810, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 130, 810, 10);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(150, 160, 10, 270);

        btnPaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/add-20-20.png"))); // NOI18N
        btnPaciente.setContentAreaFilled(false);
        btnPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPaciente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPaciente);
        btnPaciente.setBounds(360, 90, 30, 30);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(0, 160, 810, 10);

        jLObrigatorioNome3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome3.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome3.setText("*");
        getContentPane().add(jLObrigatorioNome3);
        jLObrigatorioNome3.setBounds(350, 70, 10, 30);

        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel6.setMaximumSize(new java.awt.Dimension(810, 521));
        jLabel6.setMinimumSize(new java.awt.Dimension(810, 521));
        jLabel6.setPreferredSize(new java.awt.Dimension(810, 521));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(2, 0, 810, 521);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        List<PrioridadeAtendimento> lista;
        lista = (prioridadeAtendimentoDAO.listar());
        PrioridadeAtendimentoTableModel itm = new PrioridadeAtendimentoTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Prioridade Atendimento");
        if (objetoRetorno != null) {
            prioridadeAtendimento = prioridadeAtendimentoDAO.consultarObjetoId("idPrioridadeAtendimento", objetoRetorno);
            txtPaciente.setText(prioridadeAtendimento.getPaciente().getNomePessoa());
            txtAtendimento.setText(prioridadeAtendimento.getTipoAtendimento().getNomeAtendimento());
            if (prioridadeAtendimento.getPrioridade().equalsIgnoreCase(jrAzul.getText())) {
                jrAzul.setSelected(true);
            }
            if (prioridadeAtendimento.getPrioridade().equalsIgnoreCase(jrAmarelo.getText())) {
                jrAmarelo.setSelected(true);
            }
            if (prioridadeAtendimento.getPrioridade().equalsIgnoreCase(jrLaranja.getText())) {
                jrLaranja.setSelected(true);
            }
            if (prioridadeAtendimento.getPrioridade().equalsIgnoreCase(jrVerde.getText())) {
                jrVerde.setSelected(true);
            }
            atendimento = prioridadeAtendimento.getTipoAtendimento();
            paciente = prioridadeAtendimento.getPaciente();
            btExcluir.setEnabled(true);
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        prioridadeAtendimentoDAO.excluir(prioridadeAtendimento);
        atendimento = new Atendimento();
        paciente = new Paciente();
        btLimparActionPerformed(null);
    }//GEN-LAST:event_btExcluirActionPerformed


    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (txtAtendimento.getText().equals("") || txtPaciente.getText().equals("")
                || !(jrAmarelo.isSelected() || jrAzul.isSelected() || jrLaranja.isSelected() || jrVerde.isSelected())) {
            JOptionPane.showMessageDialog(this, "Prencha todos os campos !!");
        } else {
            if (jrAzul.isSelected()) {
                prioridadeAtendimento.setPrioridade(jrAzul.getText());
            } else if (jrLaranja.isSelected()) {
                prioridadeAtendimento.setPrioridade(jrLaranja.getText());
            } else if (jrVerde.isSelected()) {
                prioridadeAtendimento.setPrioridade(jrVerde.getText());
            } else if (jrAmarelo.isSelected()) {
                prioridadeAtendimento.setPrioridade(jrAmarelo.getText());
            }
            prioridadeAtendimento.setPaciente(paciente);
            prioridadeAtendimento.setTipoAtendimento(atendimento);

            prioridadeAtendimentoDAO.salvar(prioridadeAtendimento);
            grupoPrioridade.clearSelection();
            btLimparActionPerformed(null);
            prioridadeAtendimento = new PrioridadeAtendimento();

        }
    }//GEN-LAST:event_btSalvarActionPerformed


    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void txtPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPacienteActionPerformed

    private void btnPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacienteActionPerformed
        List<Paciente> lista;
        lista = (pacienteDAO.listar());
        PacienteTableModel itm = new PacienteTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Pacinte");
        if (objetoRetorno != null) {
            paciente = pacienteDAO.consultarObjetoId("idPessoa", objetoRetorno);
            txtPaciente.setText(paciente.getNomePessoa());
        }
    }//GEN-LAST:event_btnPacienteActionPerformed


    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        Util.limparCamposGenerico(this);
        atendimento = new Atendimento();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btnAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtendimentoActionPerformed
        List<Atendimento> lista;
        lista = (atendimentoDAO.listar());
        AtendimentoTableModel itm = new AtendimentoTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Atendimento");
        if (objetoRetorno != null) {
            atendimento = atendimentoDAO.consultarObjetoId("idAtendimento", objetoRetorno);
            txtAtendimento.setText(atendimento.getNomeAtendimento());
        }
    }//GEN-LAST:event_btnAtendimentoActionPerformed

    private void txtAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAtendimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAtendimentoActionPerformed

    private void jrVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrVerdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrVerdeActionPerformed

    private void jrAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrAzulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrAzulActionPerformed

    public void addAPorraToda() {
        if (paciente != null || atendimento != null) {
            prioridadeAtendimento = new PrioridadeAtendimento();
            prioridadeAtendimento.setPaciente(paciente);
            //prioridadeAtendimento.setAtendimento(atendimento);
        } else {
            System.out.println("Selecione um paciente!");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroTriagem dialog = new CadastroTriagem(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amarelo;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JButton btnAtendimento;
    private javax.swing.JButton btnPaciente;
    private javax.swing.ButtonGroup grupoPrioridade;
    private javax.swing.JLabel jLObrigatorioNome3;
    private javax.swing.JLabel jLObrigatorioNome4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel jlNomeUsuario5;
    private javax.swing.JLabel jlNomeUsuario6;
    private javax.swing.JRadioButton jrAmarelo;
    private javax.swing.JRadioButton jrAzul;
    private javax.swing.JRadioButton jrLaranja;
    private javax.swing.JRadioButton jrVerde;
    private javax.swing.JLabel laranja;
    private javax.swing.JTextField txtAtendimento;
    private javax.swing.JTextField txtPaciente;
    private javax.swing.JLabel verde;
    private javax.swing.JLabel verde1;
    // End of variables declaration//GEN-END:variables
}
