/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registraclinic.telas;

import java.awt.Component;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import registraclinic.util.Util;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import registraclinic.aluno.Aluno;
import registraclinic.aluno.AlunoDAO;
import registraclinic.aluno.AlunoTableModel;
import registraclinic.cidade.Cidade;
import registraclinic.cidade.CidadeDAO;
import registraclinic.cidade.CidadeTableModel;
import registraclinic.funcionario.Funcionario;
import registraclinic.funcionario.FuncionarioDAO;
import registraclinic.funcionario.FuncionarioTableModel;
import registraclinic.paciente.Paciente;
import registraclinic.paciente.PacienteDAO;
import registraclinic.paciente.PacienteTableModel;
import registraclinic.supervisor.Supervisor;
import registraclinic.supervisor.SupervisorDAO;
import registraclinic.supervisor.SupervisorTableModel;

/**
 *
 * @author Karlos Oliveira
 */
public class CadastroPessoa extends javax.swing.JDialog {

    Aluno alunos = new Aluno();
    AlunoDAO alunoDAO = new AlunoDAO();
    Paciente paciente = new Paciente();
    PacienteDAO pacienteDAO = new PacienteDAO();
    Funcionario funcionario = new Funcionario();
    FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
    Supervisor supervisor = new Supervisor();
    SupervisorDAO supervisorDAO = new SupervisorDAO();
    Cidade cidade = new Cidade();
    CidadeDAO cidadeDAO = new CidadeDAO();

    SimpleDateFormat formatarData = new SimpleDateFormat("dd/MM/yyyy");
    Date date;
    private javax.swing.JPanel[] paineis;

    /**
     * Creates new form TelaCadastroUsuario
     */
    public CadastroPessoa(java.awt.Frame parent, boolean modal) {
        initComponents();
        getRootPane().setDefaultButton(btSalvar);

        btLimparActionPerformed(null);
        setModal(true);
        jtGeral.setEnabledAt(1, false);
        jtGeral.setEnabledAt(2, false);
        jtGeral.setEnabledAt(3, false);
        jtGeral.setEnabledAt(4, false);
        txtCidade.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtGeral = new javax.swing.JTabbedPane();
        jpDadosPessoais = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jlNomeUsuario2 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLObrigatorioNome3 = new javax.swing.JLabel();
        btnProduto2 = new javax.swing.JButton();
        txtRg = new javax.swing.JTextField();
        jLObrigatorioNome48 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        jLObrigatorioNome46 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLObrigatorioNome15 = new javax.swing.JLabel();
        jLObrigatorioNome12 = new javax.swing.JLabel();
        jLObrigatorioNome16 = new javax.swing.JLabel();
        jcSexo = new javax.swing.JComboBox<>();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLObrigatorioNome26 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLObrigatorioNome27 = new javax.swing.JLabel();
        txtEndNumero = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLObrigatorioNome28 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        txtNaturalidade = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        jLObrigatorioNome32 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jcEstadoCivil = new javax.swing.JComboBox<>();
        jLObrigatorioNome33 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLObrigatorioNome34 = new javax.swing.JLabel();
        txtOcupacao = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLObrigatorioNome35 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jcTipoUsuario = new javax.swing.JComboBox<>();
        jLObrigatorioNome36 = new javax.swing.JLabel();
        labelDadosPessoais = new javax.swing.JLabel();
        jpAluno = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        txtTurmaAluno = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLObrigatorioNome20 = new javax.swing.JLabel();
        jLObrigatorioNome21 = new javax.swing.JLabel();
        jLObrigatorioNome22 = new javax.swing.JLabel();
        txtEmailAluno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtLoginAluno = new javax.swing.JTextField();
        jLObrigatorioNome14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtSenhaAluno = new javax.swing.JPasswordField();
        jLObrigatorioNome17 = new javax.swing.JLabel();
        labelAluno = new javax.swing.JLabel();
        jpFuncionario = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLObrigatorioNome25 = new javax.swing.JLabel();
        txtEmailFuncionario = new javax.swing.JTextField();
        txtFuncao = new javax.swing.JTextField();
        jLObrigatorioNome38 = new javax.swing.JLabel();
        jLObrigatorioNome18 = new javax.swing.JLabel();
        txtSenhaFuncionario = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        jLObrigatorioNome19 = new javax.swing.JLabel();
        txtLoginFuncionario = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        labelFuncionario = new javax.swing.JLabel();
        jpPaciente = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLObrigatorioNome44 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtNumProntuario = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLObrigatorioNome45 = new javax.swing.JLabel();
        jLObrigatorioNome47 = new javax.swing.JLabel();
        jLObrigatorioNome49 = new javax.swing.JLabel();
        jLObrigatorioNome50 = new javax.swing.JLabel();
        txtESF = new javax.swing.JTextField();
        txtAgenteDeSaude = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        labelPaciente = new javax.swing.JLabel();
        jpSupervisor = new javax.swing.JPanel();
        jLObrigatorioNome23 = new javax.swing.JLabel();
        txtSenhaSupervisor = new javax.swing.JPasswordField();
        jLabel19 = new javax.swing.JLabel();
        jLObrigatorioNome24 = new javax.swing.JLabel();
        txtLoginSupervisor = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txtTurmaSupervisor = new javax.swing.JTextField();
        txtEspecializacao = new javax.swing.JTextField();
        jLObrigatorioNome54 = new javax.swing.JLabel();
        jLObrigatorioNome37 = new javax.swing.JLabel();
        txtEmailSupervisor = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        labelSupervisor = new javax.swing.JLabel();
        btVoltar = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 570));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jtGeral.setBackground(new java.awt.Color(65, 191, 182));
        jtGeral.setForeground(new java.awt.Color(22, 64, 61));
        jtGeral.setToolTipText("");
        jtGeral.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jtGeral.setVerifyInputWhenFocusTarget(false);

        jpDadosPessoais.setBackground(new java.awt.Color(65, 191, 182));
        jpDadosPessoais.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpDadosPessoais.setForeground(new java.awt.Color(22, 64, 61));
        jpDadosPessoais.setLayout(null);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel35.setText("RG");
        jpDadosPessoais.add(jLabel35);
        jLabel35.setBounds(180, 70, 97, 19);

        jlNomeUsuario2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario2.setText("Cidade:");
        jpDadosPessoais.add(jlNomeUsuario2);
        jlNomeUsuario2.setBounds(440, 130, 70, 20);

        txtCidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCidade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        txtCidade.setMaximumSize(new java.awt.Dimension(8, 200));
        txtCidade.setMinimumSize(new java.awt.Dimension(8, 200));
        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });
        jpDadosPessoais.add(txtCidade);
        txtCidade.setBounds(440, 150, 260, 30);

        jLObrigatorioNome3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome3.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome3.setText("*");
        jpDadosPessoais.add(jLObrigatorioNome3);
        jLObrigatorioNome3.setBounds(690, 140, 10, 10);

        btnProduto2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProduto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/add-20-20.png"))); // NOI18N
        btnProduto2.setContentAreaFilled(false);
        btnProduto2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProduto2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProduto2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProduto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduto2ActionPerformed(evt);
            }
        });
        jpDadosPessoais.add(btnProduto2);
        btnProduto2.setBounds(700, 150, 30, 30);

        txtRg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtRg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtRg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRgActionPerformed(evt);
            }
        });
        jpDadosPessoais.add(txtRg);
        txtRg.setBounds(180, 90, 170, 30);

        jLObrigatorioNome48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome48.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome48.setText("*");
        jpDadosPessoais.add(jLObrigatorioNome48);
        jLObrigatorioNome48.setBounds(340, 80, 10, 10);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel33.setText("CPF");
        jpDadosPessoais.add(jLabel33);
        jLabel33.setBounds(20, 70, 97, 19);

        txtCpf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });
        jpDadosPessoais.add(txtCpf);
        txtCpf.setBounds(20, 90, 150, 30);

        jLObrigatorioNome46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome46.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome46.setText("*");
        jpDadosPessoais.add(jLObrigatorioNome46);
        jLObrigatorioNome46.setBounds(160, 80, 10, 10);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("Nome Completo");
        jpDadosPessoais.add(jLabel2);
        jLabel2.setBounds(20, 10, 130, 19);

        txtNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jpDadosPessoais.add(txtNome);
        txtNome.setBounds(20, 30, 410, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("Sexo");
        jpDadosPessoais.add(jLabel3);
        jLabel3.setBounds(440, 10, 50, 19);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("Data Nascimento");
        jpDadosPessoais.add(jLabel7);
        jLabel7.setBounds(580, 10, 130, 19);

        jLObrigatorioNome15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome15.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome15.setText("*");
        jpDadosPessoais.add(jLObrigatorioNome15);
        jLObrigatorioNome15.setBounds(560, 20, 10, 10);

        jLObrigatorioNome12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome12.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome12.setText("*");
        jpDadosPessoais.add(jLObrigatorioNome12);
        jLObrigatorioNome12.setBounds(710, 20, 10, 10);

        jLObrigatorioNome16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome16.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome16.setText("*");
        jpDadosPessoais.add(jLObrigatorioNome16);
        jLObrigatorioNome16.setBounds(420, 20, 10, 10);

        jcSexo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "Masculino", "Feminino", "Não Definido" }));
        jcSexo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jcSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcSexoActionPerformed(evt);
            }
        });
        jpDadosPessoais.add(jcSexo);
        jcSexo.setBounds(440, 30, 130, 30);

        txtDataNascimento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        try {
            txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataNascimento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jpDadosPessoais.add(txtDataNascimento);
        txtDataNascimento.setBounds(580, 30, 140, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel12.setText("Endereço");
        jpDadosPessoais.add(jLabel12);
        jLabel12.setBounds(20, 130, 90, 19);

        txtEndereco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEndereco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });
        jpDadosPessoais.add(txtEndereco);
        txtEndereco.setBounds(20, 150, 330, 30);

        jLObrigatorioNome26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome26.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome26.setText("*");
        jpDadosPessoais.add(jLObrigatorioNome26);
        jLObrigatorioNome26.setBounds(340, 140, 10, 10);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel22.setText("N°");
        jpDadosPessoais.add(jLabel22);
        jLabel22.setBounds(360, 130, 20, 19);

        jLObrigatorioNome27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome27.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome27.setText("*");
        jpDadosPessoais.add(jLObrigatorioNome27);
        jLObrigatorioNome27.setBounds(420, 140, 10, 10);

        txtEndNumero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEndNumero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpDadosPessoais.add(txtEndNumero);
        txtEndNumero.setBounds(360, 150, 70, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel23.setText("Bairro");
        jpDadosPessoais.add(jLabel23);
        jLabel23.setBounds(20, 190, 80, 19);

        txtBairro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBairro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });
        jpDadosPessoais.add(txtBairro);
        txtBairro.setBounds(20, 210, 370, 30);

        jLObrigatorioNome28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome28.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome28.setText("*");
        jpDadosPessoais.add(jLObrigatorioNome28);
        jLObrigatorioNome28.setBounds(380, 200, 10, 10);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel24.setText("Complemento");
        jpDadosPessoais.add(jLabel24);
        jLabel24.setBounds(400, 190, 130, 19);

        txtComplemento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtComplemento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementoActionPerformed(evt);
            }
        });
        jpDadosPessoais.add(txtComplemento);
        txtComplemento.setBounds(400, 210, 320, 30);

        txtNaturalidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNaturalidade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpDadosPessoais.add(txtNaturalidade);
        txtNaturalidade.setBounds(20, 270, 190, 30);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel28.setText("Telefone");
        jpDadosPessoais.add(jLabel28);
        jLabel28.setBounds(530, 70, 65, 19);

        txtTelefone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTelefone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jpDadosPessoais.add(txtTelefone);
        txtTelefone.setBounds(530, 90, 190, 30);

        jLObrigatorioNome32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome32.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome32.setText("*");
        jpDadosPessoais.add(jLObrigatorioNome32);
        jLObrigatorioNome32.setBounds(710, 80, 10, 10);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel29.setText("Estado Civil");
        jpDadosPessoais.add(jLabel29);
        jLabel29.setBounds(360, 70, 100, 19);

        jcEstadoCivil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Viúvo(a)" }));
        jcEstadoCivil.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jcEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcEstadoCivilActionPerformed(evt);
            }
        });
        jpDadosPessoais.add(jcEstadoCivil);
        jcEstadoCivil.setBounds(360, 90, 160, 30);

        jLObrigatorioNome33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome33.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome33.setText("*");
        jpDadosPessoais.add(jLObrigatorioNome33);
        jLObrigatorioNome33.setBounds(510, 80, 10, 10);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel30.setText("Naturalidade");
        jpDadosPessoais.add(jLabel30);
        jLabel30.setBounds(20, 250, 110, 19);

        jLObrigatorioNome34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome34.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome34.setText("*");
        jpDadosPessoais.add(jLObrigatorioNome34);
        jLObrigatorioNome34.setBounds(200, 260, 10, 10);

        txtOcupacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtOcupacao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpDadosPessoais.add(txtOcupacao);
        txtOcupacao.setBounds(220, 270, 220, 30);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel31.setText("Ocupação");
        jpDadosPessoais.add(jLabel31);
        jLabel31.setBounds(220, 250, 110, 19);

        jLObrigatorioNome35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome35.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome35.setText("*");
        jpDadosPessoais.add(jLObrigatorioNome35);
        jLObrigatorioNome35.setBounds(430, 260, 10, 10);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel32.setText("Tipo de Usuário");
        jpDadosPessoais.add(jLabel32);
        jLabel32.setBounds(450, 250, 130, 19);

        jcTipoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "Aluno", "Funcionário", "Paciente", "Supervisor" }));
        jcTipoUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jcTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcTipoUsuarioActionPerformed(evt);
            }
        });
        jpDadosPessoais.add(jcTipoUsuario);
        jcTipoUsuario.setBounds(450, 270, 270, 30);

        jLObrigatorioNome36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome36.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome36.setText("*");
        jpDadosPessoais.add(jLObrigatorioNome36);
        jLObrigatorioNome36.setBounds(710, 260, 10, 10);

        labelDadosPessoais.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jpDadosPessoais.add(labelDadosPessoais);
        labelDadosPessoais.setBounds(0, 0, 750, 310);

        jtGeral.addTab("Dados Pessoais", jpDadosPessoais);

        jpAluno.setBackground(new java.awt.Color(65, 191, 182));
        jpAluno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpAluno.setForeground(new java.awt.Color(22, 64, 61));
        jpAluno.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setText("Matricula");
        jpAluno.add(jLabel11);
        jLabel11.setBounds(20, 10, 90, 19);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel15.setText("Turma");
        jpAluno.add(jLabel15);
        jLabel15.setBounds(140, 10, 60, 19);

        txtMatricula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMatricula.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });
        jpAluno.add(txtMatricula);
        txtMatricula.setBounds(20, 30, 110, 30);

        txtTurmaAluno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTurmaAluno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpAluno.add(txtTurmaAluno);
        txtTurmaAluno.setBounds(140, 30, 310, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel21.setText("Email");
        jpAluno.add(jLabel21);
        jLabel21.setBounds(460, 10, 50, 19);

        jLObrigatorioNome20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome20.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome20.setText("*");
        jpAluno.add(jLObrigatorioNome20);
        jLObrigatorioNome20.setBounds(120, 20, 10, 10);

        jLObrigatorioNome21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome21.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome21.setText("*");
        jpAluno.add(jLObrigatorioNome21);
        jLObrigatorioNome21.setBounds(720, 20, 10, 10);

        jLObrigatorioNome22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome22.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome22.setText("*");
        jpAluno.add(jLObrigatorioNome22);
        jLObrigatorioNome22.setBounds(440, 20, 10, 10);

        txtEmailAluno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEmailAluno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpAluno.add(txtEmailAluno);
        txtEmailAluno.setBounds(460, 30, 270, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Login");
        jpAluno.add(jLabel10);
        jLabel10.setBounds(20, 70, 70, 17);

        txtLoginAluno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtLoginAluno.setForeground(new java.awt.Color(22, 64, 61));
        txtLoginAluno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtLoginAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtLoginAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginAlunoActionPerformed(evt);
            }
        });
        jpAluno.add(txtLoginAluno);
        txtLoginAluno.setBounds(20, 90, 220, 30);

        jLObrigatorioNome14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome14.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome14.setText("*");
        jpAluno.add(jLObrigatorioNome14);
        jLObrigatorioNome14.setBounds(440, 80, 10, 10);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Senha");
        jpAluno.add(jLabel16);
        jLabel16.setBounds(250, 70, 70, 17);

        txtSenhaAluno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSenhaAluno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpAluno.add(txtSenhaAluno);
        txtSenhaAluno.setBounds(250, 90, 200, 30);

        jLObrigatorioNome17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome17.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome17.setText("*");
        jpAluno.add(jLObrigatorioNome17);
        jLObrigatorioNome17.setBounds(230, 80, 10, 10);

        labelAluno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jpAluno.add(labelAluno);
        labelAluno.setBounds(0, 0, 750, 310);

        jtGeral.addTab("Aluno", jpAluno);

        jpFuncionario.setBackground(new java.awt.Color(65, 191, 182));
        jpFuncionario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpFuncionario.setForeground(new java.awt.Color(22, 64, 61));
        jpFuncionario.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel13.setText("Função");
        jpFuncionario.add(jLabel13);
        jLabel13.setBounds(20, 10, 90, 19);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel26.setText("Email");
        jpFuncionario.add(jLabel26);
        jLabel26.setBounds(420, 10, 50, 19);

        jLObrigatorioNome25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome25.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome25.setText("*");
        jpFuncionario.add(jLObrigatorioNome25);
        jLObrigatorioNome25.setBounds(720, 20, 10, 10);

        txtEmailFuncionario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEmailFuncionario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpFuncionario.add(txtEmailFuncionario);
        txtEmailFuncionario.setBounds(410, 30, 320, 30);

        txtFuncao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFuncao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncaoActionPerformed(evt);
            }
        });
        jpFuncionario.add(txtFuncao);
        txtFuncao.setBounds(20, 30, 380, 30);

        jLObrigatorioNome38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome38.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome38.setText("*");
        jpFuncionario.add(jLObrigatorioNome38);
        jLObrigatorioNome38.setBounds(390, 20, 10, 10);

        jLObrigatorioNome18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome18.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome18.setText("*");
        jpFuncionario.add(jLObrigatorioNome18);
        jLObrigatorioNome18.setBounds(390, 80, 10, 10);

        txtSenhaFuncionario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSenhaFuncionario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpFuncionario.add(txtSenhaFuncionario);
        txtSenhaFuncionario.setBounds(210, 90, 190, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Senha");
        jpFuncionario.add(jLabel17);
        jLabel17.setBounds(210, 70, 70, 17);

        jLObrigatorioNome19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome19.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome19.setText("*");
        jpFuncionario.add(jLObrigatorioNome19);
        jLObrigatorioNome19.setBounds(190, 80, 10, 10);

        txtLoginFuncionario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtLoginFuncionario.setForeground(new java.awt.Color(22, 64, 61));
        txtLoginFuncionario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtLoginFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtLoginFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginFuncionarioActionPerformed(evt);
            }
        });
        jpFuncionario.add(txtLoginFuncionario);
        txtLoginFuncionario.setBounds(20, 90, 180, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Login");
        jpFuncionario.add(jLabel18);
        jLabel18.setBounds(20, 70, 70, 17);

        labelFuncionario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jpFuncionario.add(labelFuncionario);
        labelFuncionario.setBounds(0, 0, 750, 310);

        jtGeral.addTab("Funcionário", jpFuncionario);

        jpPaciente.setBackground(new java.awt.Color(65, 191, 182));
        jpPaciente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpPaciente.setForeground(new java.awt.Color(22, 64, 61));
        jpPaciente.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel14.setText("Nº Prontuário");
        jpPaciente.add(jLabel14);
        jLabel14.setBounds(20, 10, 110, 19);

        jLObrigatorioNome44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome44.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome44.setText("*");
        jpPaciente.add(jLObrigatorioNome44);
        jLObrigatorioNome44.setBounds(720, 80, 10, 10);

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel40.setText("ESF");
        jpPaciente.add(jLabel40);
        jLabel40.setBounds(230, 10, 50, 19);

        txtNumProntuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNumProntuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtNumProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumProntuarioActionPerformed(evt);
            }
        });
        jpPaciente.add(txtNumProntuario);
        txtNumProntuario.setBounds(20, 30, 200, 30);

        txtAltura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAltura.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpPaciente.add(txtAltura);
        txtAltura.setBounds(610, 90, 120, 30);

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel42.setText("Agente de Saúde");
        jpPaciente.add(jLabel42);
        jLabel42.setBounds(20, 70, 150, 19);

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel43.setText("Peso (kg)");
        jpPaciente.add(jLabel43);
        jLabel43.setBounds(490, 70, 90, 19);

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel44.setText("Altura (cm)");
        jpPaciente.add(jLabel44);
        jLabel44.setBounds(610, 70, 90, 19);

        jLObrigatorioNome45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome45.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome45.setText("*");
        jpPaciente.add(jLObrigatorioNome45);
        jLObrigatorioNome45.setBounds(210, 20, 10, 10);

        jLObrigatorioNome47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome47.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome47.setText("*");
        jpPaciente.add(jLObrigatorioNome47);
        jLObrigatorioNome47.setBounds(720, 20, 10, 10);

        jLObrigatorioNome49.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome49.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome49.setText("*");
        jpPaciente.add(jLObrigatorioNome49);
        jLObrigatorioNome49.setBounds(470, 80, 10, 10);

        jLObrigatorioNome50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome50.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome50.setText("*");
        jpPaciente.add(jLObrigatorioNome50);
        jLObrigatorioNome50.setBounds(590, 80, 10, 10);

        txtESF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtESF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpPaciente.add(txtESF);
        txtESF.setBounds(230, 30, 500, 30);

        txtAgenteDeSaude.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAgenteDeSaude.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpPaciente.add(txtAgenteDeSaude);
        txtAgenteDeSaude.setBounds(20, 90, 460, 30);

        txtPeso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPeso.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpPaciente.add(txtPeso);
        txtPeso.setBounds(490, 90, 110, 30);

        labelPaciente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jpPaciente.add(labelPaciente);
        labelPaciente.setBounds(0, 0, 750, 310);

        jtGeral.addTab("Paciente", jpPaciente);

        jpSupervisor.setBackground(new java.awt.Color(65, 191, 182));
        jpSupervisor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpSupervisor.setForeground(new java.awt.Color(22, 64, 61));
        jpSupervisor.setLayout(null);

        jLObrigatorioNome23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome23.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome23.setText("*");
        jpSupervisor.add(jLObrigatorioNome23);
        jLObrigatorioNome23.setBounds(720, 80, 10, 10);

        txtSenhaSupervisor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSenhaSupervisor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpSupervisor.add(txtSenhaSupervisor);
        txtSenhaSupervisor.setBounds(550, 90, 180, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Senha");
        jpSupervisor.add(jLabel19);
        jLabel19.setBounds(550, 70, 70, 17);

        jLObrigatorioNome24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome24.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome24.setText("*");
        jpSupervisor.add(jLObrigatorioNome24);
        jLObrigatorioNome24.setBounds(530, 80, 10, 10);

        txtLoginSupervisor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtLoginSupervisor.setForeground(new java.awt.Color(22, 64, 61));
        txtLoginSupervisor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtLoginSupervisor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtLoginSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginSupervisorActionPerformed(evt);
            }
        });
        jpSupervisor.add(txtLoginSupervisor);
        txtLoginSupervisor.setBounds(340, 90, 200, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Login");
        jpSupervisor.add(jLabel20);
        jLabel20.setBounds(340, 70, 70, 17);

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel47.setText("Turma");
        jpSupervisor.add(jLabel47);
        jLabel47.setBounds(20, 10, 90, 19);

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel48.setText("Especialização");
        jpSupervisor.add(jLabel48);
        jLabel48.setBounds(390, 10, 130, 19);

        txtTurmaSupervisor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTurmaSupervisor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtTurmaSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTurmaSupervisorActionPerformed(evt);
            }
        });
        jpSupervisor.add(txtTurmaSupervisor);
        txtTurmaSupervisor.setBounds(20, 30, 360, 30);

        txtEspecializacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEspecializacao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpSupervisor.add(txtEspecializacao);
        txtEspecializacao.setBounds(388, 31, 340, 30);

        jLObrigatorioNome54.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome54.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome54.setText("*");
        jpSupervisor.add(jLObrigatorioNome54);
        jLObrigatorioNome54.setBounds(720, 20, 10, 10);

        jLObrigatorioNome37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome37.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome37.setText("*");
        jpSupervisor.add(jLObrigatorioNome37);
        jLObrigatorioNome37.setBounds(320, 80, 10, 10);

        txtEmailSupervisor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEmailSupervisor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpSupervisor.add(txtEmailSupervisor);
        txtEmailSupervisor.setBounds(20, 90, 310, 30);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel34.setText("Email");
        jpSupervisor.add(jLabel34);
        jLabel34.setBounds(20, 70, 50, 19);

        labelSupervisor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jpSupervisor.add(labelSupervisor);
        labelSupervisor.setBounds(0, 0, 750, 320);

        jtGeral.addTab("Supervisor", jpSupervisor);

        getContentPane().add(jtGeral);
        jtGeral.setBounds(0, 120, 750, 340);

        btVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/voltar2.png"))); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.setContentAreaFilled(false);
        btVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar);
        btVoltar.setBounds(210, 480, 90, 70);

        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/pesquisa.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.setContentAreaFilled(false);
        btPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btPesquisar);
        btPesquisar.setBounds(430, 480, 100, 70);

        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/excluir_1.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setContentAreaFilled(false);
        btExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluir);
        btExcluir.setBounds(550, 480, 80, 70);

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/limpar_1.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setContentAreaFilled(false);
        btLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar);
        btLimpar.setBounds(330, 480, 80, 70);

        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/salvar_1.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setContentAreaFilled(false);
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar);
        btSalvar.setBounds(660, 480, 80, 70);

        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jLabel6.setMaximumSize(new java.awt.Dimension(700, 500));
        jLabel6.setMinimumSize(new java.awt.Dimension(700, 500));
        jLabel6.setPreferredSize(new java.awt.Dimension(700, 570));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 750, 570);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private String converterDataString(Date date) {
        SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
        return f.format(date);
    }

    public JTabbedPane retornarPainel() {
        return jtGeral;
    }

    private Date formataData(String data) {
        if (data == null || data.equals("")) {
            return null;
        }
        Date d = null;
        try {
            DateFormat formatar = new SimpleDateFormat("dd/MM/yyyy");
            d = formatar.parse(data);
        } catch (ParseException e) {

        }
        return d;
    }

    private void selecionarAba(){
        if (jcTipoUsuario.getSelectedItem().equals("Aluno")) {
            jtGeral.setSelectedComponent(jpDadosPessoais);
            jtGeral.setEnabledAt(1, true);
        } else if (jcTipoUsuario.getSelectedItem().equals("Funcionário")) {
            jtGeral.setSelectedComponent(jpDadosPessoais);
            jtGeral.setEnabledAt(2, true);
        } else if (jcTipoUsuario.getSelectedItem().equals("Paciente")) {
            jtGeral.setSelectedComponent(jpDadosPessoais);
            jtGeral.setEnabledAt(3, true);
        } else if (jcTipoUsuario.getSelectedItem().equals("Supervisor")) {
            jtGeral.setSelectedComponent(jpDadosPessoais);
            jtGeral.setEnabledAt(4, true);
        }
    }
    
    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
                
        if (jcTipoUsuario.getSelectedItem().equals("Aluno")) {
            selecionarAba();
            List<Aluno> lista;
            lista = (alunoDAO.listar());
            AlunoTableModel itm = new AlunoTableModel(lista);
            Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Aluno");
            if (objetoRetorno != null) {
                alunos = alunoDAO.consultarObjetoId("idPessoa", objetoRetorno);
                txtNome.setText(alunos.getNomePessoa());
                txtDataNascimento.setText(converterDataString(alunos.getDataNascimentoPessoa()));
                txtCpf.setText(alunos.getCpfPessoa());
                txtRg.setText(alunos.getRgPessoa());
                txtBairro.setText(alunos.getBairroPessoa());
                txtTelefone.setText(alunos.getTelefonePessoa());
                txtEndereco.setText(alunos.getEnderecoPessoa());
                txtEndNumero.setText(alunos.getEnderecoNumeroPessoa());
                txtComplemento.setText(alunos.getComplementoPessoa());
                txtNaturalidade.setText(alunos.getNaturalidadePessoa());
                txtOcupacao.setText(alunos.getOcupacaoPessoa());
                txtCidade.setText(alunos.getCidade());
                jcEstadoCivil.setSelectedItem(alunos.getEstadoCivilPessoa());
                jcSexo.setSelectedItem(alunos.getSexoPessoa());
                jcTipoUsuario.setSelectedItem(alunos.getTipoUsuario());

                txtMatricula.setText(alunos.getMatriculaAluno());
                txtTurmaAluno.setText(alunos.getTurmaAluno());
                txtEmailAluno.setText(alunos.getEmailUsuario());
                txtLoginAluno.setText(alunos.getLoginUsuario());
                txtSenhaAluno.setText(alunos.getSenhaUsuario());

                btExcluir.setEnabled(true);
            } else {
                jtGeral.setEnabledAt(1, false);
            }
        } else if (jcTipoUsuario.getSelectedItem().equals("Funcionário")) {
            selecionarAba();
            List<Funcionario> lista;
            lista = (funcionarioDAO.listar());
            FuncionarioTableModel itm = new FuncionarioTableModel(lista);
            Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Funcionário");
            if (objetoRetorno != null) {
                funcionario = funcionarioDAO.consultarObjetoId("idPessoa", objetoRetorno);
                txtNome.setText(funcionario.getNomePessoa());
                txtDataNascimento.setText(converterDataString(funcionario.getDataNascimentoPessoa()));
                txtCpf.setText(funcionario.getCpfPessoa());
                txtRg.setText(funcionario.getRgPessoa());
                txtBairro.setText(funcionario.getBairroPessoa());
                txtTelefone.setText(funcionario.getTelefonePessoa());
                txtEndereco.setText(funcionario.getEnderecoPessoa());
                txtEndNumero.setText(funcionario.getEnderecoNumeroPessoa());
                txtComplemento.setText(funcionario.getComplementoPessoa());
                txtNaturalidade.setText(funcionario.getNaturalidadePessoa());
                txtOcupacao.setText(funcionario.getOcupacaoPessoa());
                txtCidade.setText(funcionario.getCidade());
                jcEstadoCivil.setSelectedItem(funcionario.getEstadoCivilPessoa());
                jcSexo.setSelectedItem(funcionario.getSexoPessoa());
                jcTipoUsuario.setSelectedItem(funcionario.getTipoUsuario());

                txtFuncao.setText(funcionario.getFuncaoFuncionario());
                txtEmailFuncionario.setText(funcionario.getEmailUsuario());
                txtLoginFuncionario.setText(funcionario.getLoginUsuario());
                txtSenhaFuncionario.setText(funcionario.getSenhaUsuario());

                btExcluir.setEnabled(true);
            } else {
                jtGeral.setEnabledAt(2, false);
            }
        } else if (jcTipoUsuario.getSelectedItem().equals("Paciente")) {
            selecionarAba();
            List<Paciente> lista;
            lista = (pacienteDAO.listar());
            PacienteTableModel itm = new PacienteTableModel(lista);
            Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Paciente");
            if (objetoRetorno != null) {
                paciente = pacienteDAO.consultarObjetoId("idPessoa", objetoRetorno);
                txtNome.setText(paciente.getNomePessoa());
                txtDataNascimento.setText(converterDataString(paciente.getDataNascimentoPessoa()));
                txtCpf.setText(paciente.getCpfPessoa());
                txtRg.setText(paciente.getRgPessoa());
                txtBairro.setText(paciente.getBairroPessoa());
                txtTelefone.setText(paciente.getTelefonePessoa());
                txtEndereco.setText(paciente.getEnderecoPessoa());
                txtEndNumero.setText(paciente.getEnderecoNumeroPessoa());
                txtComplemento.setText(paciente.getComplementoPessoa());
                txtNaturalidade.setText(paciente.getNaturalidadePessoa());
                txtOcupacao.setText(paciente.getOcupacaoPessoa());
                txtCidade.setText(paciente.getCidade());
                jcEstadoCivil.setSelectedItem(paciente.getEstadoCivilPessoa());
                jcSexo.setSelectedItem(paciente.getSexoPessoa());

                txtNumProntuario.setText(paciente.getNumeroProntuarioPaciente());
                txtESF.setText(paciente.getPostoDeSaudePaciente());
                txtAgenteDeSaude.setText(paciente.getAgenteDeSaudePaciente());
                txtPeso.setText(paciente.getPesoPaciente());
                txtAltura.setText(paciente.getAlturaPaciente());

                btExcluir.setEnabled(true);
            } else {
                jtGeral.setEnabledAt(3, false);
            }
        } else if (jcTipoUsuario.getSelectedItem().equals("Supervisor")) {
            selecionarAba();
            List<Supervisor> lista;
            lista = (supervisorDAO.listar());
            SupervisorTableModel itm = new SupervisorTableModel(lista);
            Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Supervisor");
            if (objetoRetorno != null) {
                supervisor = supervisorDAO.consultarObjetoId("idPessoa", objetoRetorno);
                txtNome.setText(supervisor.getNomePessoa());
                txtDataNascimento.setText(converterDataString(supervisor.getDataNascimentoPessoa()));
                txtCpf.setText(supervisor.getCpfPessoa());
                txtRg.setText(supervisor.getRgPessoa());
                txtBairro.setText(supervisor.getBairroPessoa());
                txtTelefone.setText(supervisor.getTelefonePessoa());
                txtEndereco.setText(supervisor.getEnderecoPessoa());
                txtEndNumero.setText(supervisor.getEnderecoNumeroPessoa());
                txtComplemento.setText(supervisor.getComplementoPessoa());
                txtNaturalidade.setText(supervisor.getNaturalidadePessoa());
                txtOcupacao.setText(supervisor.getOcupacaoPessoa());
                txtCidade.setText(supervisor.getCidade());
                jcEstadoCivil.setSelectedItem(supervisor.getEstadoCivilPessoa());
                jcSexo.setSelectedItem(supervisor.getSexoPessoa());
                jcTipoUsuario.setSelectedItem(supervisor.getTipoUsuario());

                txtTurmaSupervisor.setText(supervisor.getTurmaSupervisor());
                txtEspecializacao.setText(supervisor.getEspecializacaoSupervisor());
                txtEmailSupervisor.setText(supervisor.getEmailUsuario());
                txtLoginSupervisor.setText(supervisor.getLoginUsuario());
                txtSenhaSupervisor.setText(supervisor.getSenhaUsuario());

                btExcluir.setEnabled(true);
            } else {
                jtGeral.setEnabledAt(4, false);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione o Tipo de Usuário para a pesquisa!",
                    "ERRO", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        if (jcTipoUsuario.getSelectedItem().equals("Aluno")) {
            alunoDAO.excluir(alunos);
            jcTipoUsuario.setSelectedIndex(0);
        } else if (jcTipoUsuario.getSelectedItem().equals("Funcionário")) {
            funcionarioDAO.excluir(funcionario);
            jcTipoUsuario.setSelectedIndex(0);
        } else if (jcTipoUsuario.getSelectedItem().equals("Paciente")) {
            pacienteDAO.excluir(paciente);
            jcTipoUsuario.setSelectedIndex(0);
        } else if (jcTipoUsuario.getSelectedItem().equals("Supervisor")) {
            supervisorDAO.excluir(supervisor);
            jcTipoUsuario.setSelectedIndex(0);
        }

        btLimparActionPerformed(null);
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        btExcluir.setEnabled(false);

        txtNome.setText("");
        txtDataNascimento.setText("");
        txtCpf.setText("");
        txtRg.setText("");
        txtBairro.setText("");
        txtTelefone.setText("");
        txtEndereco.setText("");
        txtEndNumero.setText("");
        txtComplemento.setText("");
        txtNaturalidade.setText("");
        txtOcupacao.setText("");
        txtCidade.setText("");
        jcEstadoCivil.setSelectedIndex(0);
        jcSexo.setSelectedIndex(0);
        jcTipoUsuario.setSelectedIndex(0);

        txtMatricula.setText("");
        txtTurmaAluno.setText("");
        txtEmailAluno.setText("");
        txtLoginAluno.setText("");
        txtSenhaAluno.setText("");

        txtFuncao.setText("");
        txtEmailFuncionario.setText("");
        txtLoginFuncionario.setText("");
        txtSenhaFuncionario.setText("");

        txtNumProntuario.setText("");
        txtESF.setText("");
        txtAgenteDeSaude.setText("");
        txtPeso.setText("");
        txtAltura.setText("");

        txtTurmaAluno.setText("");
        txtEspecializacao.setText("");
        txtEmailFuncionario.setText("");
        txtLoginFuncionario.setText("");
        txtSenhaFuncionario.setText("");

        alunos = new Aluno();
        funcionario = new Funcionario();
        supervisor = new Supervisor();
        paciente = new Paciente();
        jtGeral.setEnabledAt(0, true);
        jtGeral.setEnabledAt(1, false);
        jtGeral.setEnabledAt(2, false);
        jtGeral.setEnabledAt(3, false);
        jtGeral.setEnabledAt(4, false);
        jtGeral.setSelectedComponent(jpDadosPessoais);
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

        if (txtEndereco.getText().equals("")
                || txtDataNascimento.getText().equals("") || txtEndNumero.getText().equals("")
                || jcSexo.getSelectedIndex() == 0 || jcEstadoCivil.getSelectedIndex() == 0
                || txtTelefone.getText().equals("") || txtNome.getText().equals("")
                || txtBairro.getText().equals("") || txtCidade.getText().equals("")
                || txtNaturalidade.getText().equals("")
                || txtOcupacao.getText().equals("") || jcTipoUsuario.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Prencha os campos obrigatórios!!");
        } else {
            if (jcTipoUsuario.getSelectedItem().equals("Aluno")) {
                alunos.setNomePessoa(txtNome.getText().toUpperCase());
                alunos.setDataNascimentoPessoa(formataData(txtDataNascimento.getText()));
                alunos.setEnderecoPessoa(txtEndereco.getText());
                alunos.setEnderecoNumeroPessoa(txtTurmaAluno.getText());
                alunos.setTelefonePessoa(txtTelefone.getText());
                alunos.setNaturalidadePessoa(txtNaturalidade.getText());
                alunos.setSexoPessoa(jcSexo.getSelectedItem().toString());
                alunos.setEstadoCivilPessoa(jcEstadoCivil.getSelectedItem().toString());
                alunos.setBairroPessoa(txtBairro.getText());
                alunos.setOcupacaoPessoa(txtOcupacao.getText());
                alunos.setComplementoPessoa(txtComplemento.getText());
                alunos.setIdadePessoa(getIdade(formataData(txtDataNascimento.getText())));
                alunos.setCidade(cidade.getNomeCidade());
                alunos.setCpfPessoa(txtCpf.getText());
                alunos.setRgPessoa(txtRg.getText());

                alunos.setEmailUsuario(txtEmailAluno.getText());
                alunos.setLoginUsuario(txtLoginAluno.getText());
                alunos.setSenhaUsuario(txtSenhaAluno.getText());
                alunos.setTipoUsuario(jcTipoUsuario.getSelectedItem().toString());

                alunos.setTurmaAluno(txtTurmaAluno.getText());
                alunos.setMatriculaAluno(txtMatricula.getText());

                alunoDAO.salvar(alunos);
                jtGeral.setEnabledAt(1, false);
                btLimparActionPerformed(null);
            } else if (jcTipoUsuario.getSelectedItem().equals("Paciente")) {
                paciente.setNomePessoa(txtNome.getText().toUpperCase());
                paciente.setDataNascimentoPessoa(formataData(txtDataNascimento.getText()));
                paciente.setEnderecoPessoa(txtEndereco.getText());
                paciente.setEnderecoNumeroPessoa(txtEndNumero.getText());
                paciente.setTelefonePessoa(txtTelefone.getText());
                paciente.setNaturalidadePessoa(txtNaturalidade.getText());
                paciente.setSexoPessoa(jcSexo.getSelectedItem().toString());
                paciente.setEstadoCivilPessoa(jcEstadoCivil.getSelectedItem().toString());
                paciente.setCidade(cidade.getNomeCidade());

                paciente.setBairroPessoa(txtBairro.getText());
                paciente.setOcupacaoPessoa(txtOcupacao.getText());
                paciente.setComplementoPessoa(txtComplemento.getText());
                paciente.setIdadePessoa(getIdade(formataData(txtDataNascimento.getText())));
                paciente.setCpfPessoa(txtCpf.getText());
                paciente.setRgPessoa(txtRg.getText());

                paciente.setNumeroProntuarioPaciente(txtNumProntuario.getText());
                paciente.setPostoDeSaudePaciente(txtESF.getText());
                paciente.setAgenteDeSaudePaciente(txtAgenteDeSaude.getText());
                paciente.setPesoPaciente(txtPeso.getText());
                paciente.setAlturaPaciente(txtAltura.getText());

                pacienteDAO.salvar(paciente);
                jtGeral.setEnabledAt(2, false);
                btLimparActionPerformed(null);
            } else if (jcTipoUsuario.getSelectedItem().equals("Funcionário")) {
                funcionario.setNomePessoa(txtNome.getText().toUpperCase());
                funcionario.setDataNascimentoPessoa(formataData(txtDataNascimento.getText()));
                funcionario.setEnderecoPessoa(txtEndereco.getText());
                funcionario.setEnderecoNumeroPessoa(txtEndNumero.getText());
                funcionario.setTelefonePessoa(txtTelefone.getText());
                funcionario.setNaturalidadePessoa(txtNaturalidade.getText());
                funcionario.setSexoPessoa(jcSexo.getSelectedItem().toString());
                funcionario.setEstadoCivilPessoa(jcEstadoCivil.getSelectedItem().toString());
                funcionario.setCidade(cidade.getNomeCidade());
                funcionario.setBairroPessoa(txtBairro.getText());
                funcionario.setOcupacaoPessoa(txtOcupacao.getText());
                funcionario.setComplementoPessoa(txtComplemento.getText());
                funcionario.setIdadePessoa(getIdade(formataData(txtDataNascimento.getText())));
                funcionario.setCpfPessoa(txtCpf.getText());
                funcionario.setRgPessoa(txtRg.getText());

                funcionario.setEmailUsuario(txtEmailFuncionario.getText());
                funcionario.setSenhaUsuario(txtSenhaFuncionario.getText());
                funcionario.setLoginUsuario(txtLoginFuncionario.getText());
                funcionario.setTipoUsuario(jcTipoUsuario.getSelectedItem().toString());

                funcionario.setFuncaoFuncionario(txtFuncao.getText());

                funcionarioDAO.salvar(funcionario);
                jtGeral.setEnabledAt(3, false);
                btLimparActionPerformed(null);
            } else if (jcTipoUsuario.getSelectedItem().equals("Supervisor")) {
                supervisor.setNomePessoa(txtNome.getText().toUpperCase());
                supervisor.setDataNascimentoPessoa(formataData(txtDataNascimento.getText()));
                supervisor.setEnderecoPessoa(txtEndereco.getText());
                supervisor.setEnderecoNumeroPessoa(txtEndNumero.getText());
                supervisor.setTelefonePessoa(txtTelefone.getText());
                supervisor.setNaturalidadePessoa(txtNaturalidade.getText());
                supervisor.setSexoPessoa(jcSexo.getSelectedItem().toString());
                supervisor.setEstadoCivilPessoa(jcEstadoCivil.getSelectedItem().toString());
                supervisor.setCidade(cidade.getNomeCidade());
                supervisor.setBairroPessoa(txtBairro.getText());
                supervisor.setOcupacaoPessoa(txtOcupacao.getText());
                supervisor.setComplementoPessoa(txtComplemento.getText());
                supervisor.setIdadePessoa(getIdade(formataData(txtDataNascimento.getText())));
                supervisor.setCpfPessoa(txtCpf.getText());
                supervisor.setRgPessoa(txtRg.getText());

                supervisor.setEmailUsuario(txtEmailSupervisor.getText());
                supervisor.setSenhaUsuario(txtSenhaSupervisor.getText());
                supervisor.setLoginUsuario(txtLoginSupervisor.getText());
                supervisor.setTipoUsuario(jcTipoUsuario.getSelectedItem().toString());

                supervisor.setTurmaSupervisor(txtTurmaSupervisor.getText());
                supervisor.setEspecializacaoSupervisor(txtEspecializacao.getText());

                supervisorDAO.salvar(supervisor);
                jtGeral.setEnabledAt(4, false);
                btLimparActionPerformed(null);
            }
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private String getIdade(Date data) {
        Calendar dataNascimento = Calendar.getInstance();
        dataNascimento.setTime(data);
        Calendar dataAtual = Calendar.getInstance();
        Integer diferencaMes = dataAtual.get(Calendar.MONTH) - dataNascimento.get(Calendar.MONTH);
        Integer diferencaDia = dataAtual.get(Calendar.DAY_OF_MONTH) - dataNascimento.get(Calendar.DAY_OF_MONTH);
        Integer idade = (dataAtual.get(Calendar.YEAR) - dataNascimento.get(Calendar.YEAR));
        if (diferencaMes < 0 || (diferencaMes == 0 && diferencaDia < 0)) {
            idade--;
        }
        return idade.toString();

    }

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed

        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void jcSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcSexoActionPerformed

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void txtComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoActionPerformed

    private void jcEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcEstadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcEstadoCivilActionPerformed

    private void jcTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcTipoUsuarioActionPerformed
        if (jcTipoUsuario.getSelectedItem().equals("Aluno") && !txtNome.getText().equals("")) {
            jtGeral.setSelectedComponent(jpAluno);
            jtGeral.setEnabledAt(1, true);
        }
        if (jcTipoUsuario.getSelectedItem().equals("Funcionário") && !txtNome.getText().equals("")) {
            jtGeral.setSelectedComponent(jpFuncionario);
            jtGeral.setEnabledAt(2, true);
        }
        if (jcTipoUsuario.getSelectedItem().equals("Paciente") && !txtNome.getText().equals("")) {
            jtGeral.setSelectedComponent(jpPaciente);
            jtGeral.setEnabledAt(3, true);
        }
        if (jcTipoUsuario.getSelectedItem().equals("Supervisor") && !txtNome.getText().equals("")) {
            jtGeral.setSelectedComponent(jpSupervisor);
            jtGeral.setEnabledAt(4, true);
        }
        if (jcTipoUsuario.getSelectedItem().equals("-----")) {
            jtGeral.setSelectedComponent(jpDadosPessoais);
            jtGeral.setEnabledAt(1, false);
            jtGeral.setEnabledAt(2, false);
            jtGeral.setEnabledAt(3, false);
            jtGeral.setEnabledAt(4, false);
        }
    }//GEN-LAST:event_jcTipoUsuarioActionPerformed

    private void txtFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuncaoActionPerformed

    private void txtNumProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumProntuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumProntuarioActionPerformed

    private void txtTurmaSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTurmaSupervisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTurmaSupervisorActionPerformed

    private void txtLoginAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginAlunoActionPerformed

    private void txtLoginFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginFuncionarioActionPerformed

    private void txtLoginSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginSupervisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginSupervisorActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void txtRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRgActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void btnProduto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduto2ActionPerformed
        List<Cidade> lista;
        lista = (cidadeDAO.listar());
        CidadeTableModel itm = new CidadeTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Cidade");
        if (objetoRetorno != null) {
            cidade = cidadeDAO.consultarObjetoId("idCidade", objetoRetorno);

            txtCidade.setText(cidade.getNomeCidade());
            txtCidade.setEnabled(false);

        }
    }//GEN-LAST:event_btnProduto2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroPessoa dialog = new CadastroPessoa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JButton btnProduto2;
    private javax.swing.JLabel jLObrigatorioNome12;
    private javax.swing.JLabel jLObrigatorioNome14;
    private javax.swing.JLabel jLObrigatorioNome15;
    private javax.swing.JLabel jLObrigatorioNome16;
    private javax.swing.JLabel jLObrigatorioNome17;
    private javax.swing.JLabel jLObrigatorioNome18;
    private javax.swing.JLabel jLObrigatorioNome19;
    private javax.swing.JLabel jLObrigatorioNome20;
    private javax.swing.JLabel jLObrigatorioNome21;
    private javax.swing.JLabel jLObrigatorioNome22;
    private javax.swing.JLabel jLObrigatorioNome23;
    private javax.swing.JLabel jLObrigatorioNome24;
    private javax.swing.JLabel jLObrigatorioNome25;
    private javax.swing.JLabel jLObrigatorioNome26;
    private javax.swing.JLabel jLObrigatorioNome27;
    private javax.swing.JLabel jLObrigatorioNome28;
    private javax.swing.JLabel jLObrigatorioNome3;
    private javax.swing.JLabel jLObrigatorioNome32;
    private javax.swing.JLabel jLObrigatorioNome33;
    private javax.swing.JLabel jLObrigatorioNome34;
    private javax.swing.JLabel jLObrigatorioNome35;
    private javax.swing.JLabel jLObrigatorioNome36;
    private javax.swing.JLabel jLObrigatorioNome37;
    private javax.swing.JLabel jLObrigatorioNome38;
    private javax.swing.JLabel jLObrigatorioNome44;
    private javax.swing.JLabel jLObrigatorioNome45;
    private javax.swing.JLabel jLObrigatorioNome46;
    private javax.swing.JLabel jLObrigatorioNome47;
    private javax.swing.JLabel jLObrigatorioNome48;
    private javax.swing.JLabel jLObrigatorioNome49;
    private javax.swing.JLabel jLObrigatorioNome50;
    private javax.swing.JLabel jLObrigatorioNome54;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> jcEstadoCivil;
    private javax.swing.JComboBox<String> jcSexo;
    private javax.swing.JComboBox<String> jcTipoUsuario;
    private javax.swing.JLabel jlNomeUsuario2;
    private javax.swing.JPanel jpAluno;
    private javax.swing.JPanel jpDadosPessoais;
    private javax.swing.JPanel jpFuncionario;
    private javax.swing.JPanel jpPaciente;
    private javax.swing.JPanel jpSupervisor;
    private javax.swing.JTabbedPane jtGeral;
    private javax.swing.JLabel labelAluno;
    private javax.swing.JLabel labelDadosPessoais;
    private javax.swing.JLabel labelFuncionario;
    private javax.swing.JLabel labelPaciente;
    private javax.swing.JLabel labelSupervisor;
    private javax.swing.JTextField txtAgenteDeSaude;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JTextField txtESF;
    private javax.swing.JTextField txtEmailAluno;
    private javax.swing.JTextField txtEmailFuncionario;
    private javax.swing.JTextField txtEmailSupervisor;
    private javax.swing.JTextField txtEndNumero;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEspecializacao;
    private javax.swing.JTextField txtFuncao;
    private javax.swing.JTextField txtLoginAluno;
    private javax.swing.JTextField txtLoginFuncionario;
    private javax.swing.JTextField txtLoginSupervisor;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNaturalidade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumProntuario;
    private javax.swing.JTextField txtOcupacao;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtRg;
    private javax.swing.JPasswordField txtSenhaAluno;
    private javax.swing.JPasswordField txtSenhaFuncionario;
    private javax.swing.JPasswordField txtSenhaSupervisor;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JTextField txtTurmaAluno;
    private javax.swing.JTextField txtTurmaSupervisor;
    // End of variables declaration//GEN-END:variables
}
