/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registraclinic.telas;

import java.awt.Color;
import java.time.Instant;
import java.util.Date;
import registraclinic.util.Util;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import registraclinic.atendimento.Atendimento;
import registraclinic.atendimento.AtendimentoDAO;
import registraclinic.atendimento.AtendimentoTableModel;
import registraclinic.paciente.Paciente;
import registraclinic.paciente.PacienteDAO;
import registraclinic.paciente.PacienteTableModel;
//import registraclinic.traumatoortopedia.TraumatoOrtopedia;
//import registraclinic.traumatoortopedia.TraumatoOrtopediaDAO;
//import registraclinic.traumatoortopedia.TraumatoOrtopediaTableModel;
import registraclinic.triagem.Triagem;
import registraclinic.triagem.TriagemDAO;
import registraclinic.triagem.TriagemTableModel;

/**
 *
 * @author Karlos Oliveira
 */
public class CadastroTraumatoOrtopedia extends javax.swing.JDialog {

    Paciente paciente;
    PacienteDAO pacienteDAO = new PacienteDAO();
//    TraumatoOrtopedia traumatoOrtopedia = new TraumatoOrtopedia();
//    TraumatoOrtopediaDAO traumatoOrtopediaDAO = new TraumatoOrtopediaDAO();
    

    public CadastroTraumatoOrtopedia(java.awt.Frame parent, boolean modal) {
        initComponents();
        getRootPane().setDefaultButton(btSalvar);
        btLimparActionPerformed(null);
        setModal(true);
        txtPaciente.setEnabled(false);
        paciente = new Paciente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoPrioridade = new javax.swing.ButtonGroup();
        btVoltar = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        txtPa = new javax.swing.JTextField();
        txtDiagnostico = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtHistoricoFamiliar = new javax.swing.JTextArea();
        jLabel39 = new javax.swing.JLabel();
        jLObrigatorioNome42 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtHpp = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtHda = new javax.swing.JTextArea();
        jLabel37 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLObrigatorioNome40 = new javax.swing.JLabel();
        jLObrigatorioNome4 = new javax.swing.JLabel();
        jLObrigatorioNome41 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtFc = new javax.swing.JTextField();
        jlNomeUsuario6 = new javax.swing.JLabel();
        jlNomeUsuario5 = new javax.swing.JLabel();
        jLObrigatorioNome45 = new javax.swing.JLabel();
        jLObrigatorioNome44 = new javax.swing.JLabel();
        jLObrigatorioNome43 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtFr = new javax.swing.JTextField();
        txtPaciente = new javax.swing.JTextField();
        btnPaciente = new javax.swing.JButton();
        jLObrigatorioNome3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 521));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        btVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/voltar_fisio.png"))); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.setContentAreaFilled(false);
        btVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btVoltar.setDefaultCapable(false);
        btVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar);
        btVoltar.setBounds(20, 440, 80, 70);

        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/pesquisar_fisio.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.setContentAreaFilled(false);
        btPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btPesquisar);
        btPesquisar.setBounds(360, 440, 100, 70);

        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/excluir_fisio.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setContentAreaFilled(false);
        btExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluir);
        btExcluir.setBounds(500, 440, 80, 70);

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/limpar_fisio.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setContentAreaFilled(false);
        btLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar);
        btLimpar.setBounds(240, 440, 80, 70);

        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/save_fisio.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setContentAreaFilled(false);
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar);
        btSalvar.setBounds(720, 440, 80, 70);

        txtPa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(58, 100, 62), 1, true));
        txtPa.setMaximumSize(new java.awt.Dimension(8, 200));
        txtPa.setMinimumSize(new java.awt.Dimension(8, 200));
        txtPa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaActionPerformed(evt);
            }
        });
        getContentPane().add(txtPa);
        txtPa.setBounds(620, 310, 170, 30);

        txtDiagnostico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDiagnostico.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(58, 100, 62), 1, true));
        txtDiagnostico.setMaximumSize(new java.awt.Dimension(8, 200));
        txtDiagnostico.setMinimumSize(new java.awt.Dimension(8, 200));
        txtDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiagnosticoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDiagnostico);
        txtDiagnostico.setBounds(380, 120, 410, 30);

        jtHistoricoFamiliar.setColumns(20);
        jtHistoricoFamiliar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtHistoricoFamiliar.setLineWrap(true);
        jtHistoricoFamiliar.setRows(3);
        jtHistoricoFamiliar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(56, 100, 62), 1, true));
        jScrollPane3.setViewportView(jtHistoricoFamiliar);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 310, 520, 110);

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel39.setText("PA");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(590, 320, 30, 19);

        jLObrigatorioNome42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome42.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome42.setText("*");
        getContentPane().add(jLObrigatorioNome42);
        jLObrigatorioNome42.setBounds(780, 380, 10, 10);

        jtHpp.setColumns(20);
        jtHpp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtHpp.setLineWrap(true);
        jtHpp.setRows(3);
        jtHpp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(56, 100, 62), 1, true));
        jScrollPane2.setViewportView(jtHpp);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(410, 180, 380, 110);

        jtHda.setColumns(20);
        jtHda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtHda.setLineWrap(true);
        jtHda.setRows(3);
        jtHda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(56, 100, 62), 1, true));
        jScrollPane1.setViewportView(jtHda);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 180, 380, 110);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel37.setText("HDA");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(20, 160, 60, 19);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(570, 310, 10, 110);

        jLObrigatorioNome40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome40.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome40.setText("*");
        getContentPane().add(jLObrigatorioNome40);
        jLObrigatorioNome40.setBounds(390, 170, 10, 10);

        jLObrigatorioNome4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome4.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome4.setText("*");
        getContentPane().add(jLObrigatorioNome4);
        jLObrigatorioNome4.setBounds(780, 110, 10, 10);

        jLObrigatorioNome41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome41.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome41.setText("*");
        getContentPane().add(jLObrigatorioNome41);
        jLObrigatorioNome41.setBounds(780, 170, 10, 10);

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel38.setText("HPP");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(410, 160, 60, 19);

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel40.setText("História Familiar");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(20, 290, 160, 19);

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel43.setText("FC");
        getContentPane().add(jLabel43);
        jLabel43.setBounds(590, 400, 30, 19);

        txtFc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(58, 100, 62), 1, true));
        txtFc.setMaximumSize(new java.awt.Dimension(8, 200));
        txtFc.setMinimumSize(new java.awt.Dimension(8, 200));
        txtFc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFcActionPerformed(evt);
            }
        });
        getContentPane().add(txtFc);
        txtFc.setBounds(620, 390, 170, 30);

        jlNomeUsuario6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario6.setText("Diagnóstico Médico");
        getContentPane().add(jlNomeUsuario6);
        jlNomeUsuario6.setBounds(380, 100, 150, 20);

        jlNomeUsuario5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario5.setText("Paciente");
        getContentPane().add(jlNomeUsuario5);
        jlNomeUsuario5.setBounds(20, 100, 70, 20);

        jLObrigatorioNome45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome45.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome45.setText("*");
        getContentPane().add(jLObrigatorioNome45);
        jLObrigatorioNome45.setBounds(780, 340, 10, 10);

        jLObrigatorioNome44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome44.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome44.setText("*");
        getContentPane().add(jLObrigatorioNome44);
        jLObrigatorioNome44.setBounds(780, 300, 10, 10);

        jLObrigatorioNome43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome43.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome43.setText("*");
        getContentPane().add(jLObrigatorioNome43);
        jLObrigatorioNome43.setBounds(530, 300, 10, 10);

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel41.setText("Sinais Vitais");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(570, 290, 160, 19);

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel42.setText("FR");
        getContentPane().add(jLabel42);
        jLabel42.setBounds(590, 360, 30, 19);

        txtFr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFr.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(58, 100, 62), 1, true));
        txtFr.setMaximumSize(new java.awt.Dimension(8, 200));
        txtFr.setMinimumSize(new java.awt.Dimension(8, 200));
        txtFr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFrActionPerformed(evt);
            }
        });
        getContentPane().add(txtFr);
        txtFr.setBounds(620, 350, 170, 30);

        txtPaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPaciente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(58, 100, 62), 1, true));
        txtPaciente.setMaximumSize(new java.awt.Dimension(8, 200));
        txtPaciente.setMinimumSize(new java.awt.Dimension(8, 200));
        txtPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtPaciente);
        txtPaciente.setBounds(20, 120, 320, 30);

        btnPaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/add_20-20_fisio.png"))); // NOI18N
        btnPaciente.setContentAreaFilled(false);
        btnPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPaciente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPaciente);
        btnPaciente.setBounds(340, 120, 30, 30);

        jLObrigatorioNome3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome3.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome3.setText("*");
        getContentPane().add(jLObrigatorioNome3);
        jLObrigatorioNome3.setBounds(330, 100, 10, 30);

        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel6.setMaximumSize(new java.awt.Dimension(809, 521));
        jLabel6.setMinimumSize(new java.awt.Dimension(809, 521));
        jLabel6.setPreferredSize(new java.awt.Dimension(809, 521));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 810, 435);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
//        List<TraumatoOrtopedia> lista;
//        lista = (traumatoOrtopediaDAO.listar());
//        TraumatoOrtopediaTableModel itm = new TraumatoOrtopediaTableModel(lista);
//        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Traumato Ortopedia");
//        if (objetoRetorno != null) {
//            traumatoOrtopedia = traumatoOrtopediaDAO.consultarObjetoId("idTraumatoOrtopedia", objetoRetorno);
//            txtPaciente.setText(traumatoOrtopedia.getPaciente().getNomePessoa());
//
//            
//            paciente = traumatoOrtopedia.getPaciente();
//            btExcluir.setEnabled(true);
//        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
//        traumatoOrtopediaDAO.excluir(traumatoOrtopedia);
//        paciente = new Paciente();
//        btLimparActionPerformed(null);
    }//GEN-LAST:event_btExcluirActionPerformed


    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (txtPaciente.getText().equals("") || txtDiagnostico.getText().equals("") 
                || jtHda.getText().isEmpty() || jtHpp.getText().isEmpty()
                || jtHistoricoFamiliar.getText().isEmpty() || txtPa.getText().equals("")
                || txtFr.getText().equals("") || txtFc.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Prencha todos os campos !!");
        } else {
            
//            traumatoOrtopedia.setPaciente(paciente);
//            traumatoOrtopedia.setDiagnosticoMedico(txtDiagnostico.getText());
//            traumatoOrtopedia.setHda(jtHda.getText());
//            
//            traumatoOrtopediaDAO.salvar(traumatoOrtopedia);
//            grupoPrioridade.clearSelection();
//            btLimparActionPerformed(null);
//            traumatoOrtopedia = new TraumatoOrtopedia();

        }
    }//GEN-LAST:event_btSalvarActionPerformed


    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void txtPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPacienteActionPerformed

    private void btnPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacienteActionPerformed
        List<Paciente> lista;
        lista = (pacienteDAO.listar());
        PacienteTableModel itm = new PacienteTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Pacinte");
        if (objetoRetorno != null) {
            paciente = pacienteDAO.consultarObjetoId("idPessoa", objetoRetorno);
            txtPaciente.setText(paciente.getNomePessoa());
        }
    }//GEN-LAST:event_btnPacienteActionPerformed


    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
//        Util.limparCamposGenerico(this);
//        grupoPrioridade.clearSelection();
//        traumatoOrtopedia = new TraumatoOrtopedia();
//        paciente = new Paciente();

    }//GEN-LAST:event_btLimparActionPerformed

    private void txtDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiagnosticoActionPerformed

    private void txtPaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaActionPerformed

    private void txtFrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFrActionPerformed

    private void txtFcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFcActionPerformed

//    public void addAPorraToda() {
//        if (paciente != null) {
//            traumatoOrtopedia = new TraumatoOrtopedia();
//            traumatoOrtopedia.setPaciente(paciente);
//            //prioridadeAtendimento.setAtendimento(atendimento);
//        } else {
//            System.out.println("Selecione um paciente!");
//        }
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroTraumatoOrtopedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroTraumatoOrtopedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroTraumatoOrtopedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroTraumatoOrtopedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroTraumatoOrtopedia dialog = new CadastroTraumatoOrtopedia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JButton btnPaciente;
    private javax.swing.ButtonGroup grupoPrioridade;
    private javax.swing.JLabel jLObrigatorioNome3;
    private javax.swing.JLabel jLObrigatorioNome4;
    private javax.swing.JLabel jLObrigatorioNome40;
    private javax.swing.JLabel jLObrigatorioNome41;
    private javax.swing.JLabel jLObrigatorioNome42;
    private javax.swing.JLabel jLObrigatorioNome43;
    private javax.swing.JLabel jLObrigatorioNome44;
    private javax.swing.JLabel jLObrigatorioNome45;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlNomeUsuario5;
    private javax.swing.JLabel jlNomeUsuario6;
    private javax.swing.JTextArea jtHda;
    private javax.swing.JTextArea jtHistoricoFamiliar;
    private javax.swing.JTextArea jtHpp;
    private javax.swing.JTextField txtDiagnostico;
    private javax.swing.JTextField txtFc;
    private javax.swing.JTextField txtFr;
    private javax.swing.JTextField txtPa;
    private javax.swing.JTextField txtPaciente;
    // End of variables declaration//GEN-END:variables
}
