/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registraclinic.telas;

import registraclinic.atendimento.Atendimento;
import registraclinic.atendimento.AtendimentoDAO;
import registraclinic.atendimento.AtendimentoTableModel;
import registraclinic.usuario.Usuario;
import registraclinic.util.Util;
import java.util.List;
import javax.swing.JOptionPane;
import registraclinic.paciente.Paciente;
import registraclinic.paciente.PacienteDAO;
import registraclinic.paciente.PacienteTableModel;

/**
 *
 * @author root
 */
public class TraumatoOrtopedia extends javax.swing.JDialog {

    Paciente paciente = new Paciente();
    PacienteDAO pacienteDAO = new PacienteDAO();

    public TraumatoOrtopedia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        btAvaliacaoPostural.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlNomeUsuario5 = new javax.swing.JLabel();
        btDiagnosticoCinetico = new javax.swing.JButton();
        txtPaciente = new javax.swing.JTextField();
        btPerimetria = new javax.swing.JButton();
        btExamesComplementares = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btnPaciente = new javax.swing.JButton();
        jLObrigatorioNome3 = new javax.swing.JLabel();
        btAnamnese = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        btGoniometria = new javax.swing.JButton();
        btGrauForca = new javax.swing.JButton();
        btAvaliacaoPostural = new javax.swing.JButton();
        jLFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(600, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel1.setLayout(null);

        jlNomeUsuario5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario5.setText("Paciente");
        jPanel1.add(jlNomeUsuario5);
        jlNomeUsuario5.setBounds(20, 70, 70, 20);

        btDiagnosticoCinetico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btDiagnosticoCinetico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/pesquisar_fisio.png"))); // NOI18N
        btDiagnosticoCinetico.setText("Diagnóstico Cinético Funcional");
        btDiagnosticoCinetico.setContentAreaFilled(false);
        btDiagnosticoCinetico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btDiagnosticoCinetico.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btDiagnosticoCinetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDiagnosticoCineticoActionPerformed(evt);
            }
        });
        jPanel1.add(btDiagnosticoCinetico);
        btDiagnosticoCinetico.setBounds(300, 260, 297, 50);

        txtPaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPaciente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(58, 100, 62), 1, true));
        txtPaciente.setMaximumSize(new java.awt.Dimension(8, 200));
        txtPaciente.setMinimumSize(new java.awt.Dimension(8, 200));
        txtPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtPaciente);
        txtPaciente.setBounds(20, 90, 540, 30);

        btPerimetria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPerimetria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/limpar_fisio.png"))); // NOI18N
        btPerimetria.setText("Perimetria");
        btPerimetria.setContentAreaFilled(false);
        btPerimetria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btPerimetria.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btPerimetria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPerimetriaActionPerformed(evt);
            }
        });
        jPanel1.add(btPerimetria);
        btPerimetria.setBounds(0, 200, 160, 50);

        btExamesComplementares.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btExamesComplementares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/excluir_fisio.png"))); // NOI18N
        btExamesComplementares.setText("Exames Complementares");
        btExamesComplementares.setContentAreaFilled(false);
        btExamesComplementares.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btExamesComplementares.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btExamesComplementares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExamesComplementaresActionPerformed(evt);
            }
        });
        jPanel1.add(btExamesComplementares);
        btExamesComplementares.setBounds(300, 200, 260, 50);

        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/save_fisio.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setContentAreaFilled(false);
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btSalvar);
        btSalvar.setBounds(510, 420, 80, 70);

        btnPaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/add_20-20_fisio.png"))); // NOI18N
        btnPaciente.setContentAreaFilled(false);
        btnPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPaciente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnPaciente);
        btnPaciente.setBounds(560, 90, 30, 30);

        jLObrigatorioNome3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome3.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome3.setText("*");
        jPanel1.add(jLObrigatorioNome3);
        jLObrigatorioNome3.setBounds(550, 80, 10, 10);

        btAnamnese.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAnamnese.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/voltar_fisio.png"))); // NOI18N
        btAnamnese.setText("Anamnese");
        btAnamnese.setContentAreaFilled(false);
        btAnamnese.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btAnamnese.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btAnamnese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnamneseActionPerformed(evt);
            }
        });
        jPanel1.add(btAnamnese);
        btAnamnese.setBounds(0, 140, 160, 50);

        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/excluir_fisio.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setContentAreaFilled(false);
        btExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btExcluir);
        btExcluir.setBounds(390, 420, 80, 70);

        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/pesquisar_fisio.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.setContentAreaFilled(false);
        btPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(btPesquisar);
        btPesquisar.setBounds(250, 420, 100, 70);

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/limpar_fisio.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setContentAreaFilled(false);
        btLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btLimpar);
        btLimpar.setBounds(140, 420, 80, 70);

        btVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/voltar_fisio.png"))); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.setContentAreaFilled(false);
        btVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btVoltar.setDefaultCapable(false);
        btVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btVoltar);
        btVoltar.setBounds(10, 420, 80, 70);

        btGoniometria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btGoniometria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/limpar_fisio.png"))); // NOI18N
        btGoniometria.setText("Goniometria");
        btGoniometria.setContentAreaFilled(false);
        btGoniometria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btGoniometria.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btGoniometria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGoniometriaActionPerformed(evt);
            }
        });
        jPanel1.add(btGoniometria);
        btGoniometria.setBounds(0, 260, 170, 50);

        btGrauForca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btGrauForca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/pesquisar_fisio.png"))); // NOI18N
        btGrauForca.setText("Grau de Força");
        btGrauForca.setContentAreaFilled(false);
        btGrauForca.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btGrauForca.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btGrauForca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGrauForcaActionPerformed(evt);
            }
        });
        jPanel1.add(btGrauForca);
        btGrauForca.setBounds(0, 320, 181, 50);

        btAvaliacaoPostural.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAvaliacaoPostural.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registraclinic/imagens/excluir_fisio.png"))); // NOI18N
        btAvaliacaoPostural.setText("Avaliação Postural");
        btAvaliacaoPostural.setContentAreaFilled(false);
        btAvaliacaoPostural.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btAvaliacaoPostural.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btAvaliacaoPostural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAvaliacaoPosturalActionPerformed(evt);
            }
        });
        jPanel1.add(btAvaliacaoPostural);
        btAvaliacaoPostural.setBounds(300, 140, 210, 50);

        jLFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLFundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLFundo.setMaximumSize(new java.awt.Dimension(600, 500));
        jLFundo.setMinimumSize(new java.awt.Dimension(600, 500));
        jLFundo.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel1.add(jLFundo);
        jLFundo.setBounds(0, 0, 600, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btAnamneseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnamneseActionPerformed
        dispose();
    }//GEN-LAST:event_btAnamneseActionPerformed

    private void btGrauForcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGrauForcaActionPerformed
    }//GEN-LAST:event_btGrauForcaActionPerformed

    private void btAvaliacaoPosturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAvaliacaoPosturalActionPerformed
        btLimparActionPerformed(null);
    }//GEN-LAST:event_btAvaliacaoPosturalActionPerformed

    private void btGoniometriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGoniometriaActionPerformed
        Util.limparCamposGenerico(this);
        btAvaliacaoPostural.setEnabled(false);
    }//GEN-LAST:event_btGoniometriaActionPerformed

    private void txtPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPacienteActionPerformed

    private void btnPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacienteActionPerformed
        List<Paciente> lista;
        lista = (pacienteDAO.listar());
        PacienteTableModel itm = new PacienteTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Pacinte");
        if (objetoRetorno != null) {
            paciente = pacienteDAO.consultarObjetoId("idPessoa", objetoRetorno);
            txtPaciente.setText(paciente.getNomePessoa());
        }
    }//GEN-LAST:event_btnPacienteActionPerformed

    private void btExamesComplementaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExamesComplementaresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btExamesComplementaresActionPerformed

    private void btDiagnosticoCineticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDiagnosticoCineticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDiagnosticoCineticoActionPerformed

    private void btPerimetriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPerimetriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btPerimetriaActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (true) {
            JOptionPane.showMessageDialog(this, "Prencha todos os campos !!");
        } else {

            //            triagem.setPaciente(paciente);
            //            triagem.setTipoAtendimento(atendimento);
            //            triagem.setDataTriagem(new Date());
            //            triagemDAO.salvar(triagem);
            //            grupoPrioridade.clearSelection();
            //            btLimparActionPerformed(null);
            //            triagem = new Triagem();

        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        //        triagemDAO.excluir(triagem);

        btLimparActionPerformed(null);
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        //        List<Triagem> lista;
        //        lista = (triagemDAO.listar());
        //        TriagemTableModel itm = new TriagemTableModel(lista);
        //        Object objetoRetorno = PesquisaTriagem.exibeTela(itm, "Triagem");
        //        if (objetoRetorno != null) {
            //            triagem = triagemDAO.consultarObjetoId("idTriagem", objetoRetorno);
            //            atendimento = triagem.getTipoAtendimento();
            //            paciente = triagem.getPaciente();
            //            btExcluir.setEnabled(true);
            //        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        Util.limparCamposGenerico(this);
        //        triagem = new Triagem();
        //        paciente = new Paciente();
        //        atendimento = new Atendimento();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TraumatoOrtopedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TraumatoOrtopedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TraumatoOrtopedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TraumatoOrtopedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TraumatoOrtopedia dialog = new TraumatoOrtopedia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnamnese;
    private javax.swing.JButton btAvaliacaoPostural;
    private javax.swing.JButton btDiagnosticoCinetico;
    private javax.swing.JButton btExamesComplementares;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btGoniometria;
    private javax.swing.JButton btGrauForca;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPerimetria;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JButton btnPaciente;
    private javax.swing.JLabel jLFundo;
    private javax.swing.JLabel jLObrigatorioNome3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlNomeUsuario5;
    private javax.swing.JTextField txtPaciente;
    // End of variables declaration//GEN-END:variables
}
